/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@cutpoint/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildDiscoveryDomainModule,
  buildGovernanceDomainModule,
  buildIdentityDomainModule,
  buildInterventionsDomainModule,
  buildLabellingDomainModule,
  buildMarketsDomainModule,
} from "../domains/index.js";
import type {
  DiscoveryDomainModule,
  GovernanceDomainModule,
  IdentityDomainModule,
  InterventionsDomainModule,
  LabellingDomainModule,
  MarketsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private discoveryModule: DiscoveryDomainModule | null = null;
  private governanceModule: GovernanceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private interventionsModule: InterventionsDomainModule | null = null;
  private labellingModule: LabellingDomainModule | null = null;
  private marketsModule: MarketsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get discovery domain module
   */
  getDiscoveryDependencies(): DiscoveryDomainModule {
    if (!this.discoveryModule) {
      this.discoveryModule = buildDiscoveryDomainModule(this.dynamoClient);
    }
    return this.discoveryModule;
  }

  /**
   * Get governance domain module
   */
  getGovernanceDependencies(): GovernanceDomainModule {
    if (!this.governanceModule) {
      this.governanceModule = buildGovernanceDomainModule(this.dynamoClient);
    }
    return this.governanceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get interventions domain module
   */
  getInterventionsDependencies(): InterventionsDomainModule {
    if (!this.interventionsModule) {
      this.interventionsModule = buildInterventionsDomainModule(this.dynamoClient);
    }
    return this.interventionsModule;
  }

  /**
   * Get labelling domain module
   */
  getLabellingDependencies(): LabellingDomainModule {
    if (!this.labellingModule) {
      this.labellingModule = buildLabellingDomainModule(this.dynamoClient);
    }
    return this.labellingModule;
  }

  /**
   * Get markets domain module
   */
  getMarketsDependencies(): MarketsDomainModule {
    if (!this.marketsModule) {
      this.marketsModule = buildMarketsDomainModule(this.dynamoClient);
    }
    return this.marketsModule;
  }

  clearDiscoveryDependencies(): void { this.discoveryModule = null; }
  clearGovernanceDependencies(): void { this.governanceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearInterventionsDependencies(): void { this.interventionsModule = null; }
  clearLabellingDependencies(): void { this.labellingModule = null; }
  clearMarketsDependencies(): void { this.marketsModule = null; }

  getDiscoveryDependenciesForRequest(): DiscoveryDomainModule {
    return this.getDiscoveryDependencies();
  }

  getGovernanceDependenciesForRequest(): GovernanceDomainModule {
    return this.getGovernanceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getInterventionsDependenciesForRequest(): InterventionsDomainModule {
    return this.getInterventionsDependencies();
  }

  getLabellingDependenciesForRequest(): LabellingDomainModule {
    return this.getLabellingDependencies();
  }

  getMarketsDependenciesForRequest(): MarketsDomainModule {
    return this.getMarketsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.discoveryModule = null;
    this.governanceModule = null;
    this.identityModule = null;
    this.interventionsModule = null;
    this.labellingModule = null;
    this.marketsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
