/**
 * Discovery DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Discovery Domain Module - Composition root
 *
 * DDD: Composition root for discovery domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AdjudicationRepositoryAdapter,
  CandidateRepositoryAdapter,
  DependencyMapRepositoryAdapter,
  EdgeRepositoryAdapter,
} from "@cutpoint/adapters/discovery";
import { getIdGeneratorService } from "@cutpoint/adapters";
import type { AdapterDynamoDBClient } from "@cutpoint/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAdjudicateChainCandidate,
  ExecuteGetChainCandidate,
  ExecuteGetDependencyMap,
  ExecuteListChainCandidates,
  ExecuteListDependencyEdges,
} from "@cutpoint/services/discovery/usecases";
// Ports (interfaces)
import type {
  AdjudicationRepository,
  CandidateRepository,
  DependencyMapRepository,
  EdgeRepository,
} from "@cutpoint/services/discovery/ports";

export interface DiscoveryDomainModule {
  repos: {
    adjudications: AdjudicationRepository;
    candidates: CandidateRepository;
    dependencyMaps: DependencyMapRepository;
    edges: EdgeRepository;
  };
  useCases: {
    adjudications: {
      get: ExecuteAdjudicateChainCandidate;
    };
    candidates: {
      get: ExecuteGetChainCandidate;
      list: ExecuteListChainCandidates;
    };
    dependencyMaps: {
      get: ExecuteGetDependencyMap;
    };
    edges: {
      list: ExecuteListDependencyEdges;
    };
  };
}

export function buildDiscoveryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DiscoveryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      adjudications?: AdjudicationRepository;
      candidates?: CandidateRepository;
      dependencyMaps?: DependencyMapRepository;
      edges?: EdgeRepository;
    } = {};

    obj.adjudications = new AdjudicationRepositoryAdapter(dynamoClient);
    obj.candidates = new CandidateRepositoryAdapter(dynamoClient);
    obj.dependencyMaps = new DependencyMapRepositoryAdapter(dynamoClient);
    obj.edges = new EdgeRepositoryAdapter(dynamoClient);
    return {
      adjudications: obj.adjudications!,
      candidates: obj.candidates!,
      dependencyMaps: obj.dependencyMaps!,
      edges: obj.edges!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    adjudications: {
      get: new ExecuteAdjudicateChainCandidate(executionContext, idGenerator, repos.adjudications),
    },
    candidates: {
      get: new ExecuteGetChainCandidate(executionContext, idGenerator, repos.candidates),
      list: new ExecuteListChainCandidates(executionContext, idGenerator, repos.candidates),
    },
    dependencyMaps: {
      get: new ExecuteGetDependencyMap(executionContext, idGenerator, repos.dependencyMaps),
    },
    edges: {
      list: new ExecuteListDependencyEdges(executionContext, idGenerator, repos.edges),
    },
  };
  return { repos, useCases: useCases as DiscoveryDomainModule["useCases"] };
}
