/**
 * AdjudicationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdjudicationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AdjudicationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AdjudicationRepository,
} from "@cutpoint/services/discovery";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AdjudicationRepositoryDdb } from "./adjudication-repository.ddb.js";

/**
 * AdjudicationRepositoryAdapter
 *
 * Implements AdjudicationRepository port for infrastructure layer.
 */
export class AdjudicationRepositoryAdapter implements AdjudicationRepository {
  private readonly ddb: AdjudicationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AdjudicationRepositoryDdb(this.dynamoClient);
  }

  async adjudicateChainCandidate(input: Parameters<AdjudicationRepository['adjudicateChainCandidate']>[0]): Promise<Awaited<ReturnType<AdjudicationRepository['adjudicateChainCandidate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.adjudicateChainCandidate(input);
  }
}
