/**
 * CandidateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CandidateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CandidateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CandidateRepository,
} from "@cutpoint/services/discovery";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CandidateRepositoryDdb } from "./candidate-repository.ddb.js";

/**
 * CandidateRepositoryAdapter
 *
 * Implements CandidateRepository port for infrastructure layer.
 */
export class CandidateRepositoryAdapter implements CandidateRepository {
  private readonly ddb: CandidateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CandidateRepositoryDdb(this.dynamoClient);
  }

  async listChainCandidates(input: Parameters<CandidateRepository['listChainCandidates']>[0]): Promise<Awaited<ReturnType<CandidateRepository['listChainCandidates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listChainCandidates(input);
  }

  async getChainCandidate(input: Parameters<CandidateRepository['getChainCandidate']>[0]): Promise<Awaited<ReturnType<CandidateRepository['getChainCandidate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getChainCandidate(input);
  }
}
