/**
 * DependencyMapRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DependencyMapRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DependencyMapRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DependencyMapRepository,
} from "@cutpoint/services/discovery";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DependencyMapRepositoryDdb } from "./dependency-map-repository.ddb.js";

/**
 * DependencyMapRepositoryAdapter
 *
 * Implements DependencyMapRepository port for infrastructure layer.
 */
export class DependencyMapRepositoryAdapter implements DependencyMapRepository {
  private readonly ddb: DependencyMapRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DependencyMapRepositoryDdb(this.dynamoClient);
  }

  async getDependencyMap(input: Parameters<DependencyMapRepository['getDependencyMap']>[0]): Promise<Awaited<ReturnType<DependencyMapRepository['getDependencyMap']>>> {
    try {
      return await this.ddb.getDependencyMap(input);
    } catch {
      const inputExt = (input ?? {}) as Record<string, unknown>;
      const marketId = String(inputExt.marketId ?? '');
      return {
        data: {
          marketId,
          edges: [],
          hubCategories: [],
          coverageFloorShare: 0,
          coverageIsFloor: true,
        },
        meta: {
          correlationId: (inputExt.correlationId as string) || `dsc_empty`,
          timestamp: new Date().toISOString(),
        },
      } as any;
    }
  }
}
