/**
 * EdgeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EdgeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EdgeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EdgeRepository,
} from "@cutpoint/services/discovery";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EdgeRepositoryDdb } from "./edge-repository.ddb.js";

/**
 * EdgeRepositoryAdapter
 *
 * Implements EdgeRepository port for infrastructure layer.
 */
export class EdgeRepositoryAdapter implements EdgeRepository {
  private readonly ddb: EdgeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EdgeRepositoryDdb(this.dynamoClient);
  }

  async listDependencyEdges(input: Parameters<EdgeRepository['listDependencyEdges']>[0]): Promise<Awaited<ReturnType<EdgeRepository['listDependencyEdges']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDependencyEdges(input);
  }
}
