/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./adjudication-repository.ddb.js";
export * from "./candidate-repository.ddb.js";
export * from "./dependency-map-repository.ddb.js";
export * from "./edge-repository.ddb.js";
export * from "./adjudication-repository.adapter.js";
export * from "./candidate-repository.adapter.js";
export * from "./dependency-map-repository.adapter.js";
export * from "./edge-repository.adapter.js";
