/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Labelling Domain Use Cases
 * 
 * List of all use case names for the labelling domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const LABELLING_USE_CASES = [
  "executeCreateAnnotationBatch",
  "executeGetLabellerAgreement",
  "executeGetTaxonomy",
  "executeListAnnotationBatches",
  "executeListClassificationRuns",
  "executePublishTaxonomyVersion",
  "executeSubmitAnnotationLabels"
] as const;
