/**
 * Adjudication DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Adjudication DTOs
 *
 * DDD: Application DTOs for Adjudication use cases.
 */

import type { AdjudicateChainCandidateParams, AdjudicateChainCandidateRequestInput } from "@cutpoint/core/discovery/types";

export type AdjudicateChainCandidateInput = AdjudicateChainCandidateParams & AdjudicateChainCandidateRequestInput;

export type AdjudicateChainCandidateOutput = {};
