/**
 * Candidate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Candidate DTOs
 *
 * DDD: Application DTOs for Candidate use cases.
 */

import type { GetChainCandidateParams, ListChainCandidatesParams } from "@cutpoint/core/discovery/types";

export type ListChainCandidatesInput = ListChainCandidatesParams;

export type GetChainCandidateInput = GetChainCandidateParams;

export type ListChainCandidatesOutput = {};

export type GetChainCandidateOutput = {};
