/**
 * DependencyMap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DependencyMap DTOs
 *
 * DDD: Application DTOs for DependencyMap use cases.
 */

import type { GetDependencyMapParams } from "@cutpoint/core/discovery/types";

export type GetDependencyMapInput = GetDependencyMapParams;

export type GetDependencyMapOutput = {};
