/**
 * Edge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Edge DTOs
 *
 * DDD: Application DTOs for Edge use cases.
 */

import type { ListDependencyEdgesParams } from "@cutpoint/core/discovery/types";

export type ListDependencyEdgesInput = ListDependencyEdgesParams;

export type ListDependencyEdgesOutput = {};
