/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { candidateRoutes } from "./candidate.routes.js";
export { interventionRoutes } from "./intervention.routes.js";
export { outcomeRoutes } from "./outcome.routes.js";
