/**
 * Routes for Intervention
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listInterventions, selectIntervention } from "../handlers/intervention.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function interventionRoutes(fastify: FastifyInstance) {
  // GET /v1/interventions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/interventions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInterventionsDependenciesForRequest();
        await listInterventions(request, reply, deps);
      });
    }
  );


  // POST /v1/interventions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/interventions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInterventionsDependenciesForRequest();
        await selectIntervention(request, reply, deps);
      });
    }
  );


}
