/**
 * Routes for Outcome
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { recordInterventionOutcome } from "../handlers/outcome.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function outcomeRoutes(fastify: FastifyInstance) {
  // POST /v1/interventions/{interventionId}/outcome (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/interventions/:interventionId/outcome",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { interventionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInterventionsDependenciesForRequest();
        await recordInterventionOutcome(request, reply, deps);
      });
    }
  );


}
