/**
 * AgreementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AgreementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AgreementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AgreementRepository,
} from "@cutpoint/services/labelling";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AgreementRepositoryDdb } from "./agreement-repository.ddb.js";

/**
 * AgreementRepositoryAdapter
 *
 * Implements AgreementRepository port for infrastructure layer.
 */
export class AgreementRepositoryAdapter implements AgreementRepository {
  private readonly ddb: AgreementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AgreementRepositoryDdb(this.dynamoClient);
  }

  async getLabellerAgreement(input: Parameters<AgreementRepository['getLabellerAgreement']>[0]): Promise<Awaited<ReturnType<AgreementRepository['getLabellerAgreement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLabellerAgreement(input);
  }
}
