/**
 * BatchRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BatchRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BatchRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BatchRepository,
} from "@cutpoint/services/labelling";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BatchRepositoryDdb } from "./batch-repository.ddb.js";

/**
 * BatchRepositoryAdapter
 *
 * Implements BatchRepository port for infrastructure layer.
 */
export class BatchRepositoryAdapter implements BatchRepository {
  private readonly ddb: BatchRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BatchRepositoryDdb(this.dynamoClient);
  }

  async listAnnotationBatches(input: Parameters<BatchRepository['listAnnotationBatches']>[0]): Promise<Awaited<ReturnType<BatchRepository['listAnnotationBatches']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnnotationBatches(input);
  }

  async createAnnotationBatch(input: Parameters<BatchRepository['createAnnotationBatch']>[0]): Promise<Awaited<ReturnType<BatchRepository['createAnnotationBatch']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAnnotationBatch(input);
  }
}
