/**
 * ClassificationRunRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClassificationRunRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ClassificationRunRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ClassificationRunRepository,
} from "@cutpoint/services/labelling";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ClassificationRunRepositoryDdb } from "./classification-run-repository.ddb.js";

/**
 * ClassificationRunRepositoryAdapter
 *
 * Implements ClassificationRunRepository port for infrastructure layer.
 */
export class ClassificationRunRepositoryAdapter implements ClassificationRunRepository {
  private readonly ddb: ClassificationRunRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ClassificationRunRepositoryDdb(this.dynamoClient);
  }

  async listClassificationRuns(input: Parameters<ClassificationRunRepository['listClassificationRuns']>[0]): Promise<Awaited<ReturnType<ClassificationRunRepository['listClassificationRuns']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listClassificationRuns(input);
  }
}
