/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./agreement-repository.ddb.js";
export * from "./batch-repository.ddb.js";
export * from "./classification-run-repository.ddb.js";
export * from "./label-repository.ddb.js";
export * from "./taxonomy-repository.ddb.js";
export * from "./agreement-repository.adapter.js";
export * from "./batch-repository.adapter.js";
export * from "./classification-run-repository.adapter.js";
export * from "./label-repository.adapter.js";
export * from "./taxonomy-repository.adapter.js";
export * from "./version-publisher.adapter.js";
