/**
 * LabelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LabelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LabelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LabelRepository,
} from "@cutpoint/services/labelling";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LabelRepositoryDdb } from "./label-repository.ddb.js";

/**
 * LabelRepositoryAdapter
 *
 * Implements LabelRepository port for infrastructure layer.
 */
export class LabelRepositoryAdapter implements LabelRepository {
  private readonly ddb: LabelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LabelRepositoryDdb(this.dynamoClient);
  }

  async submitAnnotationLabels(input: Parameters<LabelRepository['submitAnnotationLabels']>[0]): Promise<Awaited<ReturnType<LabelRepository['submitAnnotationLabels']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitAnnotationLabels(input);
  }
}
