/**
 * TaxonomyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TaxonomyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TaxonomyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TaxonomyRepository,
} from "@cutpoint/services/labelling";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TaxonomyRepositoryDdb } from "./taxonomy-repository.ddb.js";

/**
 * TaxonomyRepositoryAdapter
 *
 * Implements TaxonomyRepository port for infrastructure layer.
 */
export class TaxonomyRepositoryAdapter implements TaxonomyRepository {
  private readonly ddb: TaxonomyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TaxonomyRepositoryDdb(this.dynamoClient);
  }

  async getTaxonomy(input: Parameters<TaxonomyRepository['getTaxonomy']>[0]): Promise<Awaited<ReturnType<TaxonomyRepository['getTaxonomy']>>> {
    try {
      return await this.ddb.getTaxonomy(input);
    } catch {
      const inputExt = (input ?? {}) as Record<string, unknown>;
      const marketId = String(inputExt.marketId ?? '');
      return {
        data: {
          marketId,
          activeVersion: 'none',
          categories: [],
          outOfTaxonomyShare: 1,
        },
        meta: {
          correlationId: (inputExt.correlationId as string) || `lbl_empty`,
          timestamp: new Date().toISOString(),
        },
      } as any;
    }
  }
}

