/**
 * PublicationHold Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { PublicationHoldEntity } from "@cutpoint/core/governance/models/index.js";
import { governanceSchemas } from "@cutpoint/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createPublicationHold(overrides: Partial<PublicationHoldEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    appliedAt: overrides.appliedAt ?? new Date().toISOString(),
    cause: overrides.cause ?? "drift_threshold_breached",
    marketId: overrides.marketId ?? `mkt_${ulid().toLowerCase()}`,
    publicationHoldId: overrides.publicationHoldId ?? `hld_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return governanceSchemas.PublicationHold.parse(raw);
}

export function publicationHoldBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPublicationHold(overrides));
}
