/**
 * Repository interface for PublicationHold
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PublicationHoldEntity
} from "../models/publication-hold.entity.js";
import type {
  ListPublicationHoldsParams
} from "../types/index.js";
/**
 * PublicationHoldRepository Interface
 */
export interface PublicationHoldRepository extends ReadRepository<PublicationHoldEntity, string, ListPublicationHoldsParams> {

}
