/**
 * Handlers for Candidate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InterventionsDomainModule } from "../dependencies/interventions-ddd.dependencies.js";
import type { ListInterventionCandidatesInput } from "@cutpoint/services/interventions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/interventions/candidates
 * Operation: listInterventionCandidates
 */
export async function listInterventionCandidates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], marketId?: string | string[], harmMetric?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InterventionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListInterventionCandidatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.candidates.list.execute(input);
  return reply.code(200).send(result);
}


