/**
 * Handlers for Outcome
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InterventionsDomainModule } from "../dependencies/interventions-ddd.dependencies.js";
import type { RecordInterventionOutcomeInput } from "@cutpoint/services/interventions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/interventions/{interventionId}/outcome
 * Operation: recordInterventionOutcome
 */
export async function recordInterventionOutcome(
  request: FastifyRequest<{ Params: { interventionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InterventionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordInterventionOutcomeInput = {
    interventionId: request.params.interventionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.outcomes.get.execute(input);
  return reply.code(201).send(result);
}


