/**
 * Interventions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Interventions Domain Module - Composition root
 *
 * DDD: Composition root for interventions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CandidateRepositoryAdapter,
  InterventionRepositoryAdapter,
  OutcomeRepositoryAdapter,
} from "@cutpoint/adapters/interventions";
import { getIdGeneratorService } from "@cutpoint/adapters";
import type { AdapterDynamoDBClient } from "@cutpoint/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListInterventionCandidates,
  ExecuteListInterventions,
  ExecuteRecordInterventionOutcome,
  ExecuteSelectIntervention,
} from "@cutpoint/services/interventions/usecases";
// Ports (interfaces)
import type {
  CandidateRepository,
  InterventionRepository,
  OutcomeRepository,
} from "@cutpoint/services/interventions/ports";

export interface InterventionsDomainModule {
  repos: {
    candidates: CandidateRepository;
    interventions: InterventionRepository;
    outcomes: OutcomeRepository;
  };
  useCases: {
    candidates: {
      list: ExecuteListInterventionCandidates;
    };
    interventions: {
      get: ExecuteSelectIntervention;
      list: ExecuteListInterventions;
    };
    outcomes: {
      get: ExecuteRecordInterventionOutcome;
    };
  };
}

export function buildInterventionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): InterventionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      candidates?: CandidateRepository;
      interventions?: InterventionRepository;
      outcomes?: OutcomeRepository;
    } = {};

    obj.candidates = new CandidateRepositoryAdapter(dynamoClient);
    obj.interventions = new InterventionRepositoryAdapter(dynamoClient);
    obj.outcomes = new OutcomeRepositoryAdapter(dynamoClient);
    return {
      candidates: obj.candidates!,
      interventions: obj.interventions!,
      outcomes: obj.outcomes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    candidates: {
      list: new ExecuteListInterventionCandidates(executionContext, idGenerator, repos.candidates),
    },
    interventions: {
      get: new ExecuteSelectIntervention(executionContext, idGenerator, repos.interventions),
      list: new ExecuteListInterventions(executionContext, idGenerator, repos.interventions),
    },
    outcomes: {
      get: new ExecuteRecordInterventionOutcome(executionContext, idGenerator, repos.outcomes),
    },
  };
  return { repos, useCases: useCases as InterventionsDomainModule["useCases"] };
}
