/**
 * ListInterventions handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listInterventions } from "@cutpoint/api-server/domains/interventions/handlers";
import type { InterventionsDDDDependencies } from "@cutpoint/api-server/domains/interventions";
import { createIntervention as createInterventionEntity } from "@cutpoint/factories/interventions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { INTERVENTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListInterventions", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InterventionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InterventionsDDDDependencies>(
      INTERVENTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createInterventionEntity({ orgId }),
      createInterventionEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListInterventions, "execute").mockResolvedValue(useCaseResult);

    await listInterventions(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListInterventions.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
