/**
 * SelectIntervention handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { selectIntervention } from "@cutpoint/api-server/domains/interventions/handlers";
import type { InterventionsDDDDependencies } from "@cutpoint/api-server/domains/interventions";
import { createIntervention as createInterventionEntity } from "@cutpoint/factories/interventions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { INTERVENTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("SelectIntervention", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InterventionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InterventionsDDDDependencies>(
      INTERVENTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createInterventionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSelectIntervention, "execute").mockResolvedValue(useCaseResult);

    await selectIntervention(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSelectIntervention.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
