/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health is registered in src/index.ts (Cutpoint-branded sandbox status).

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "discovery", "governance", "identity", "interventions", "labelling", "markets"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      discovery: [{ method: "GET", path: "/v1/chains/candidates" }, { method: "GET", path: "/v1/chains/candidates/:candidateId" }, { method: "POST", path: "/v1/chains/candidates/:candidateId/adjudication" }, { method: "GET", path: "/v1/dependencies/edges" }, { method: "GET", path: "/v1/markets/:marketId/dependency-map" }],
      governance: [{ method: "GET", path: "/v1/assurance/markets/:marketId/coverage" }, { method: "GET", path: "/v1/assurance/markets/:marketId/drift" }, { method: "GET", path: "/v1/assurance/publication-holds" }, { method: "POST", path: "/v1/evidence/packages" }, { method: "GET", path: "/v1/evidence/packages/:packageId" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      interventions: [{ method: "GET", path: "/v1/interventions/candidates" }, { method: "GET", path: "/v1/interventions" }, { method: "POST", path: "/v1/interventions" }, { method: "POST", path: "/v1/interventions/:interventionId/outcome" }],
      labelling: [{ method: "GET", path: "/v1/markets/:marketId/taxonomy" }, { method: "POST", path: "/v1/markets/:marketId/taxonomy/versions" }, { method: "GET", path: "/v1/annotation/batches" }, { method: "POST", path: "/v1/annotation/batches" }, { method: "POST", path: "/v1/annotation/batches/:batchId/labels" }, { method: "GET", path: "/v1/annotation/batches/:batchId/agreement" }, { method: "GET", path: "/v1/classification-runs" }],
      markets: [{ method: "GET", path: "/v1/markets" }, { method: "POST", path: "/v1/markets" }, { method: "GET", path: "/v1/markets/:marketId" }, { method: "GET", path: "/v1/markets/:marketId/corpora" }, { method: "POST", path: "/v1/markets/:marketId/corpora" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "Protected routes accept X-API-Key (demo: ddd_demo_local_dev_key) or Bearer JWT from /v0/auth/login",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/", description: "Cutpoint API console (browser)" },
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Product domains are under /v1/*. Identity under /v0/*. Local sandbox uses in-memory Dynamo when CUTPOINT_SANDBOX=1.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
