/**
 * ListCorpora DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListCorporaParams } from "@cutpoint/core/markets";

export function createListCorporaRequest(overrides: Partial<ListCorporaParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
