/**
 * ClassificationRun Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/labelling.openapi.types.js";
import { schemas } from "../schemas/labelling.schemas.js";

/**
 * Entity: ClassificationRunEntity
 * Description: Represents the ClassificationRun domain model.
 * Source: schemas.ClassificationRun
 * Type: Domain Entity (API)
 */
export const ClassificationRunEntitySchema = schemas.ClassificationRun;
export type ClassificationRunEntity = components["schemas"]["ClassificationRun"];
