/**
 * Taxonomy Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/labelling.openapi.types.js";
import { schemas } from "../schemas/labelling.schemas.js";

/**
 * Entity: TaxonomyEntity
 * Description: Represents the Taxonomy domain model.
 * Source: schemas.Taxonomy
 * Type: Domain Entity (API)
 */
export const TaxonomyEntitySchema = schemas.Taxonomy;
export type TaxonomyEntity = components["schemas"]["Taxonomy"];
