/**
 * Repository interface for Intervention
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  InterventionEntity
} from "../models/intervention.entity.js";
import type {
  ListInterventionsParams,
  Intervention
} from "../types/index.js";
/**
 * InterventionRepository Interface
 */
export interface InterventionRepository extends CreateReadRepository<InterventionEntity, Intervention, string, ListInterventionsParams> {

}
