/**
 * CandidateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CandidateRepository Port
 *
 * DDD: Application port for candidaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListInterventionCandidatesInput, ListInterventionCandidatesOutput } from "../dto/candidate.dto";
export interface CandidateRepository {
  listInterventionCandidates(input: ListInterventionCandidatesInput): Promise<ListInterventionCandidatesOutput>;
}

export type { ListInterventionCandidatesInput, ListInterventionCandidatesOutput } from "../dto/candidate.dto";
