/**
 * InterventionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InterventionRepository Port
 *
 * DDD: Application port for interventionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListInterventionsInput, ListInterventionsOutput, SelectInterventionInput, SelectInterventionOutput } from "../dto/intervention.dto";
export interface InterventionRepository {
  listInterventions(input: ListInterventionsInput): Promise<ListInterventionsOutput>;
  selectIntervention(input: SelectInterventionInput): Promise<SelectInterventionOutput>;
}

export type { ListInterventionsInput, ListInterventionsOutput, SelectInterventionInput, SelectInterventionOutput } from "../dto/intervention.dto";
