/**
 * ListMarket DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListMarketsParams } from "@cutpoint/core/markets";

export function createListMarketRequest(overrides: Partial<ListMarketsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
