/**
 * Drift DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Drift DTOs
 *
 * DDD: Application DTOs for Drift use cases.
 */

import type { GetDriftAssessmentParams } from "@cutpoint/core/governance/types";

export type GetDriftAssessmentInput = GetDriftAssessmentParams;

export type GetDriftAssessmentOutput = {};
