/**
 * Package DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Package DTOs
 *
 * DDD: Application DTOs for Package use cases.
 */

import type { GetEvidencePackageParams, SealEvidencePackageRequestInput } from "@cutpoint/core/governance/types";

export type SealEvidencePackageInput = SealEvidencePackageRequestInput;

export type GetEvidencePackageInput = GetEvidencePackageParams;

export type SealEvidencePackageOutput = {};

export type GetEvidencePackageOutput = {};
