/**
 * PublicationHold DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PublicationHold DTOs
 *
 * DDD: Application DTOs for PublicationHold use cases.
 */

import type { ListPublicationHoldsParams } from "@cutpoint/core/governance/types";

export type ListPublicationHoldsInput = ListPublicationHoldsParams;

export type ListPublicationHoldsOutput = {};
