/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitored markets */
        get: operations["listMarkets"];
        put?: never;
        /** Register a market with onboarding labelling budget */
        post: operations["registerMarket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{marketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get market with budget and publication state */
        get: operations["getMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{marketId}/corpora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List corpora for a market */
        get: operations["listCorpora"];
        put?: never;
        /**
         * Ingest a licensed corpus
         * @description Ingest a licensed corpus. Rejected unless lawful basis, licence terms, and a retention window are supplied, and unless pseudonymisation is requested.
         */
        post: operations["ingestCorpus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Prefixed market id */
        MarketId: string;
        Market: {
            /** @description Prefixed market id */
            marketId: string;
            name: string;
            /** @description Primary forum language, used to route fluent labellers */
            language: string;
            /** @enum {string} */
            status: "onboarding" | "labelling" | "active" | "held" | "exited";
            /**
             * @description Committed labelling budget for this market
             * @example 8500
             */
            onboardingLabelBudgetPosts?: number;
            labelledPosts?: number;
            annotationEffortSeconds?: number;
            activeTaxonomyVersion?: string;
            publicationHeld?: boolean;
            /** Format: date-time */
            firstAdjudicatedChainAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MarketListData: {
            items: {
                /** @description Prefixed market id */
                marketId: string;
                name: string;
                /** @description Primary forum language, used to route fluent labellers */
                language: string;
                /** @enum {string} */
                status: "onboarding" | "labelling" | "active" | "held" | "exited";
                /**
                 * @description Committed labelling budget for this market
                 * @example 8500
                 */
                onboardingLabelBudgetPosts?: number;
                labelledPosts?: number;
                annotationEffortSeconds?: number;
                activeTaxonomyVersion?: string;
                publicationHeld?: boolean;
                /** Format: date-time */
                firstAdjudicatedChainAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        MarketListResponse: {
            data: {
                items: {
                    /** @description Prefixed market id */
                    marketId: string;
                    name: string;
                    /** @description Primary forum language, used to route fluent labellers */
                    language: string;
                    /** @enum {string} */
                    status: "onboarding" | "labelling" | "active" | "held" | "exited";
                    /**
                     * @description Committed labelling budget for this market
                     * @example 8500
                     */
                    onboardingLabelBudgetPosts?: number;
                    labelledPosts?: number;
                    annotationEffortSeconds?: number;
                    activeTaxonomyVersion?: string;
                    publicationHeld?: boolean;
                    /** Format: date-time */
                    firstAdjudicatedChainAt?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        MarketCreate: {
            name: string;
            language: string;
            onboardingLabelBudgetPosts: number;
            /**
             * Format: float
             * @description Publication is held when holdout F1 falls below this value
             */
            driftThresholdF1?: number;
        };
        MarketResponse: {
            data: {
                /** @description Prefixed market id */
                marketId: string;
                name: string;
                /** @description Primary forum language, used to route fluent labellers */
                language: string;
                /** @enum {string} */
                status: "onboarding" | "labelling" | "active" | "held" | "exited";
                /**
                 * @description Committed labelling budget for this market
                 * @example 8500
                 */
                onboardingLabelBudgetPosts?: number;
                labelledPosts?: number;
                annotationEffortSeconds?: number;
                activeTaxonomyVersion?: string;
                publicationHeld?: boolean;
                /** Format: date-time */
                firstAdjudicatedChainAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description Prefixed corpus id */
        CorpusId: string;
        SourceLicence: {
            /** @enum {string} */
            lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
            licenceTerms: string;
            redistributionPermitted?: boolean;
            /** @default false */
            publicIndexingPermitted: boolean;
        };
        RetentionPolicy: {
            /** @description Retention for raw posts and replies */
            rawRetentionDays: number;
            /** @description Retention for pseudonymised labels, adjudications, and edges */
            derivedRetentionDays?: number;
            /** @default true */
            purgeOnExpiry: boolean;
        };
        Corpus: {
            /** @description Prefixed corpus id */
            corpusId: string;
            /** @description Prefixed market id */
            marketId: string;
            /** @enum {string} */
            status: "accepted" | "pseudonymising" | "available" | "expired" | "purged";
            threadCount?: number;
            replyCount?: number;
            uniqueActorCount?: number;
            /** Format: date */
            coverageStart?: string;
            /** Format: date */
            coverageEnd?: string;
            licence?: {
                /** @enum {string} */
                lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                licenceTerms: string;
                redistributionPermitted?: boolean;
                /** @default false */
                publicIndexingPermitted: boolean;
            };
            retention?: {
                /** @description Retention for raw posts and replies */
                rawRetentionDays: number;
                /** @description Retention for pseudonymised labels, adjudications, and edges */
                derivedRetentionDays?: number;
                /** @default true */
                purgeOnExpiry: boolean;
            };
            /** Format: date-time */
            retentionExpiresAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CorpusListData: {
            items: {
                /** @description Prefixed corpus id */
                corpusId: string;
                /** @description Prefixed market id */
                marketId: string;
                /** @enum {string} */
                status: "accepted" | "pseudonymising" | "available" | "expired" | "purged";
                threadCount?: number;
                replyCount?: number;
                uniqueActorCount?: number;
                /** Format: date */
                coverageStart?: string;
                /** Format: date */
                coverageEnd?: string;
                licence?: {
                    /** @enum {string} */
                    lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                    licenceTerms: string;
                    redistributionPermitted?: boolean;
                    /** @default false */
                    publicIndexingPermitted: boolean;
                };
                retention?: {
                    /** @description Retention for raw posts and replies */
                    rawRetentionDays: number;
                    /** @description Retention for pseudonymised labels, adjudications, and edges */
                    derivedRetentionDays?: number;
                    /** @default true */
                    purgeOnExpiry: boolean;
                };
                /** Format: date-time */
                retentionExpiresAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        CorpusListResponse: {
            data: {
                items: {
                    /** @description Prefixed corpus id */
                    corpusId: string;
                    /** @description Prefixed market id */
                    marketId: string;
                    /** @enum {string} */
                    status: "accepted" | "pseudonymising" | "available" | "expired" | "purged";
                    threadCount?: number;
                    replyCount?: number;
                    uniqueActorCount?: number;
                    /** Format: date */
                    coverageStart?: string;
                    /** Format: date */
                    coverageEnd?: string;
                    licence?: {
                        /** @enum {string} */
                        lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                        licenceTerms: string;
                        redistributionPermitted?: boolean;
                        /** @default false */
                        publicIndexingPermitted: boolean;
                    };
                    retention?: {
                        /** @description Retention for raw posts and replies */
                        rawRetentionDays: number;
                        /** @description Retention for pseudonymised labels, adjudications, and edges */
                        derivedRetentionDays?: number;
                        /** @default true */
                        purgeOnExpiry: boolean;
                    };
                    /** Format: date-time */
                    retentionExpiresAt?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        CorpusIngest: {
            /** @description Opaque handle to the licensed archive, never inline content */
            payloadReference: string;
            licence: {
                /** @enum {string} */
                lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                licenceTerms: string;
                redistributionPermitted?: boolean;
                /** @default false */
                publicIndexingPermitted: boolean;
            };
            retention: {
                /** @description Retention for raw posts and replies */
                rawRetentionDays: number;
                /** @description Retention for pseudonymised labels, adjudications, and edges */
                derivedRetentionDays?: number;
                /** @default true */
                purgeOnExpiry: boolean;
            };
            /** @default true */
            pseudonymiseActors: boolean;
            /** Format: date */
            coverageStart?: string;
            /** Format: date */
            coverageEnd?: string;
        };
        CorpusResponse: {
            data: {
                /** @description Prefixed corpus id */
                corpusId: string;
                /** @description Prefixed market id */
                marketId: string;
                /** @enum {string} */
                status: "accepted" | "pseudonymising" | "available" | "expired" | "purged";
                threadCount?: number;
                replyCount?: number;
                uniqueActorCount?: number;
                /** Format: date */
                coverageStart?: string;
                /** Format: date */
                coverageEnd?: string;
                licence?: {
                    /** @enum {string} */
                    lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                    licenceTerms: string;
                    redistributionPermitted?: boolean;
                    /** @default false */
                    publicIndexingPermitted: boolean;
                };
                retention?: {
                    /** @description Retention for raw posts and replies */
                    rawRetentionDays: number;
                    /** @description Retention for pseudonymised labels, adjudications, and edges */
                    derivedRetentionDays?: number;
                    /** @default true */
                    purgeOnExpiry: boolean;
                };
                /** Format: date-time */
                retentionExpiresAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMarkets: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                language?: string;
                status?: "onboarding" | "labelling" | "active" | "held" | "exited";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitored markets page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /** @description Prefixed market id */
                                marketId: string;
                                name: string;
                                /** @description Primary forum language, used to route fluent labellers */
                                language: string;
                                /** @enum {string} */
                                status: "onboarding" | "labelling" | "active" | "held" | "exited";
                                /**
                                 * @description Committed labelling budget for this market
                                 * @example 8500
                                 */
                                onboardingLabelBudgetPosts?: number;
                                labelledPosts?: number;
                                annotationEffortSeconds?: number;
                                activeTaxonomyVersion?: string;
                                publicationHeld?: boolean;
                                /** Format: date-time */
                                firstAdjudicatedChainAt?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    registerMarket: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    language: string;
                    onboardingLabelBudgetPosts: number;
                    /**
                     * Format: float
                     * @description Publication is held when holdout F1 falls below this value
                     */
                    driftThresholdF1?: number;
                };
            };
        };
        responses: {
            /** @description Market registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Prefixed market id */
                            marketId: string;
                            name: string;
                            /** @description Primary forum language, used to route fluent labellers */
                            language: string;
                            /** @enum {string} */
                            status: "onboarding" | "labelling" | "active" | "held" | "exited";
                            /**
                             * @description Committed labelling budget for this market
                             * @example 8500
                             */
                            onboardingLabelBudgetPosts?: number;
                            labelledPosts?: number;
                            annotationEffortSeconds?: number;
                            activeTaxonomyVersion?: string;
                            publicationHeld?: boolean;
                            /** Format: date-time */
                            firstAdjudicatedChainAt?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                marketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Prefixed market id */
                            marketId: string;
                            name: string;
                            /** @description Primary forum language, used to route fluent labellers */
                            language: string;
                            /** @enum {string} */
                            status: "onboarding" | "labelling" | "active" | "held" | "exited";
                            /**
                             * @description Committed labelling budget for this market
                             * @example 8500
                             */
                            onboardingLabelBudgetPosts?: number;
                            labelledPosts?: number;
                            annotationEffortSeconds?: number;
                            activeTaxonomyVersion?: string;
                            publicationHeld?: boolean;
                            /** Format: date-time */
                            firstAdjudicatedChainAt?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listCorpora: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                marketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Corpora page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /** @description Prefixed corpus id */
                                corpusId: string;
                                /** @description Prefixed market id */
                                marketId: string;
                                /** @enum {string} */
                                status: "accepted" | "pseudonymising" | "available" | "expired" | "purged";
                                threadCount?: number;
                                replyCount?: number;
                                uniqueActorCount?: number;
                                /** Format: date */
                                coverageStart?: string;
                                /** Format: date */
                                coverageEnd?: string;
                                licence?: {
                                    /** @enum {string} */
                                    lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                                    licenceTerms: string;
                                    redistributionPermitted?: boolean;
                                    /** @default false */
                                    publicIndexingPermitted: boolean;
                                };
                                retention?: {
                                    /** @description Retention for raw posts and replies */
                                    rawRetentionDays: number;
                                    /** @description Retention for pseudonymised labels, adjudications, and edges */
                                    derivedRetentionDays?: number;
                                    /** @default true */
                                    purgeOnExpiry: boolean;
                                };
                                /** Format: date-time */
                                retentionExpiresAt?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingestCorpus: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                marketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Opaque handle to the licensed archive, never inline content */
                    payloadReference: string;
                    licence: {
                        /** @enum {string} */
                        lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                        licenceTerms: string;
                        redistributionPermitted?: boolean;
                        /** @default false */
                        publicIndexingPermitted?: boolean;
                    };
                    retention: {
                        /** @description Retention for raw posts and replies */
                        rawRetentionDays: number;
                        /** @description Retention for pseudonymised labels, adjudications, and edges */
                        derivedRetentionDays?: number;
                        /** @default true */
                        purgeOnExpiry?: boolean;
                    };
                    /** @default true */
                    pseudonymiseActors?: boolean;
                    /** Format: date */
                    coverageStart?: string;
                    /** Format: date */
                    coverageEnd?: string;
                };
            };
        };
        responses: {
            /** @description Corpus accepted for pseudonymised intake */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Prefixed corpus id */
                            corpusId: string;
                            /** @description Prefixed market id */
                            marketId: string;
                            /** @enum {string} */
                            status: "accepted" | "pseudonymising" | "available" | "expired" | "purged";
                            threadCount?: number;
                            replyCount?: number;
                            uniqueActorCount?: number;
                            /** Format: date */
                            coverageStart?: string;
                            /** Format: date */
                            coverageEnd?: string;
                            licence?: {
                                /** @enum {string} */
                                lawfulBasis: "public_posting_scrape" | "commercial_agreement" | "research_agreement" | "law_enforcement_disclosure";
                                licenceTerms: string;
                                redistributionPermitted?: boolean;
                                /** @default false */
                                publicIndexingPermitted: boolean;
                            };
                            retention?: {
                                /** @description Retention for raw posts and replies */
                                rawRetentionDays: number;
                                /** @description Retention for pseudonymised labels, adjudications, and edges */
                                derivedRetentionDays?: number;
                                /** @default true */
                                purgeOnExpiry: boolean;
                            };
                            /** Format: date-time */
                            retentionExpiresAt?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
