/**
 * ExecutePublishTaxonomyVersion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishTaxonomyVersion Use Case
 *
 * DDD: Application use case for get Version.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishTaxonomyVersionInput, PublishTaxonomyVersionOutput } from "../dto/version.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { TaxonomyRepository, VersionPublisher } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePublishTaxonomyVersion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly version: VersionPublisher,
    private readonly taxonomy: TaxonomyRepository
  ) {}

  async execute(input: PublishTaxonomyVersionInput): Promise<PublishTaxonomyVersionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lblId();

    // All field names extracted from OpenAPI spec: categories, changeSummary
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).marketId) {
      throw new ValidationError("marketId is required");
    }
    const marketId = (input as any).marketId;

    // Publish via VersionPublisher port (pass correlation ID for response meta)
    const entity = await this.version.publishTaxonomyVersion({
      ...(input as any),
      marketId,
      orgId: this.context.getOrgId(),
      correlationId,
    } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${marketId}`);
    }

    return entity as PublishTaxonomyVersionOutput;
  }
}
