/**
 * ExecuteListClassificationRuns - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListClassificationRuns Use Case
 *
 * DDD: Application use case for list ClassificationRun.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListClassificationRunsInput, ListClassificationRunsOutput } from "../dto/classification-run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { ClassificationRunRepository } from "../ports";

export class ExecuteListClassificationRuns {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly classificationRun: ClassificationRunRepository
  ) {}

  async execute(input: ListClassificationRunsInput): Promise<ListClassificationRunsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lblId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.classificationRun.listClassificationRuns({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListClassificationRunsOutput;
  }
}
