/**
 * ExecuteSubmitAnnotationLabels - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitAnnotationLabels Use Case
 *
 * DDD: Application use case for create Label.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitAnnotationLabelsInput, SubmitAnnotationLabelsOutput } from "../dto/label.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { LabelRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitAnnotationLabels {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly label: LabelRepository
  ) {}

  async execute(input: SubmitAnnotationLabelsInput): Promise<SubmitAnnotationLabelsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lblId();

    // All field names extracted from OpenAPI spec: effortSeconds, postLabels, replyLabels
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.replyLabels) {
      throw new ValidationError("replyLabels is required");
    }
    if (!input.postLabels) {
      throw new ValidationError("postLabels is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (labelling domain)
    const entityId = this.idGenerator.lblId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.label.submitAnnotationLabels({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitAnnotationLabelsOutput;
  }
}
