/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CoverageRepositoryAdapter,
  DriftRepositoryAdapter,
  PackageRepositoryAdapter,
  PublicationHoldRepositoryAdapter,
} from "@cutpoint/adapters/governance";
import { getIdGeneratorService } from "@cutpoint/adapters";
import type { AdapterDynamoDBClient } from "@cutpoint/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetCoverageAssessment,
  ExecuteGetDriftAssessment,
  ExecuteGetEvidencePackage,
  ExecuteListPublicationHolds,
  ExecuteSealEvidencePackage,
} from "@cutpoint/services/governance/usecases";
// Ports (interfaces)
import type {
  CoverageRepository,
  DriftRepository,
  PackageRepository,
  PublicationHoldRepository,
} from "@cutpoint/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    coverages: CoverageRepository;
    drifts: DriftRepository;
    packages: PackageRepository;
    publicationHolds: PublicationHoldRepository;
  };
  useCases: {
    coverages: {
      get: ExecuteGetCoverageAssessment;
    };
    drifts: {
      get: ExecuteGetDriftAssessment;
    };
    packages: {
      get: ExecuteGetEvidencePackage;
      seal: ExecuteSealEvidencePackage;
    };
    publicationHolds: {
      list: ExecuteListPublicationHolds;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      coverages?: CoverageRepository;
      drifts?: DriftRepository;
      packages?: PackageRepository;
      publicationHolds?: PublicationHoldRepository;
    } = {};

    obj.coverages = new CoverageRepositoryAdapter(dynamoClient);
    obj.drifts = new DriftRepositoryAdapter(dynamoClient);
    obj.packages = new PackageRepositoryAdapter(dynamoClient);
    obj.publicationHolds = new PublicationHoldRepositoryAdapter(dynamoClient);
    return {
      coverages: obj.coverages!,
      drifts: obj.drifts!,
      packages: obj.packages!,
      publicationHolds: obj.publicationHolds!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    coverages: {
      get: new ExecuteGetCoverageAssessment(executionContext, idGenerator, repos.coverages),
    },
    drifts: {
      get: new ExecuteGetDriftAssessment(executionContext, idGenerator, repos.drifts),
    },
    packages: {
      get: new ExecuteGetEvidencePackage(executionContext, idGenerator, repos.packages),
      seal: new ExecuteSealEvidencePackage(executionContext, idGenerator, repos.packages),
    },
    publicationHolds: {
      list: new ExecuteListPublicationHolds(executionContext, idGenerator, repos.publicationHolds),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
