/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @cutpoint/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@cutpoint/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@cutpoint/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@cutpoint/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@cutpoint/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@cutpoint/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _discovery from "./discovery/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _interventions from "./interventions/index.js";
import * as _labelling from "./labelling/index.js";
import * as _markets from "./markets/index.js";

// Export as namespaces
export const _shared = __shared;
export const discovery = _discovery;
export const governance = _governance;
export const identity = _identity;
export const interventions = _interventions;
export const labelling = _labelling;
export const markets = _markets;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@cutpoint/core"; activity.types.*
//   - Direct exports: import * from "@cutpoint/core/activity/types/index.js"
//   - Direct exports: import * from "@cutpoint/core/activity/repositories/index.js"
//   - Direct exports: import * from "@cutpoint/core/activity/models/index.js"
//   - Direct exports: import * from "@cutpoint/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Discovery Service
export { schemas as DiscoverySchemas } from "./discovery/schemas/discovery.schemas.js";

// Governance Service
export { schemas as GovernanceSchemas } from "./governance/schemas/governance.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Interventions Service
export { schemas as InterventionsSchemas } from "./interventions/schemas/interventions.schemas.js";

// Labelling Service
export { schemas as LabellingSchemas } from "./labelling/schemas/labelling.schemas.js";

// Markets Service
export { schemas as MarketsSchemas } from "./markets/schemas/markets.schemas.js";

