/**
 * CoverageRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CoverageRepository Port
 *
 * DDD: Application port for coveragerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCoverageAssessmentInput, GetCoverageAssessmentOutput } from "../dto/coverage.dto";
export interface CoverageRepository {
  getCoverageAssessment(input: GetCoverageAssessmentInput): Promise<GetCoverageAssessmentOutput>;
}

export type { GetCoverageAssessmentInput, GetCoverageAssessmentOutput } from "../dto/coverage.dto";
