/**
 * DriftRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DriftRepository Port
 *
 * DDD: Application port for driftrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDriftAssessmentInput, GetDriftAssessmentOutput } from "../dto/drift.dto";
export interface DriftRepository {
  getDriftAssessment(input: GetDriftAssessmentInput): Promise<GetDriftAssessmentOutput>;
}

export type { GetDriftAssessmentInput, GetDriftAssessmentOutput } from "../dto/drift.dto";
