/**
 * PackageRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PackageRepository Port
 *
 * DDD: Application port for packagerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEvidencePackageInput, GetEvidencePackageOutput, SealEvidencePackageInput, SealEvidencePackageOutput } from "../dto/package.dto";
export interface PackageRepository {
  sealEvidencePackage(input: SealEvidencePackageInput): Promise<SealEvidencePackageOutput>;
  getEvidencePackage(input: GetEvidencePackageInput): Promise<GetEvidencePackageOutput>;
}

export type { GetEvidencePackageInput, GetEvidencePackageOutput, SealEvidencePackageInput, SealEvidencePackageOutput } from "../dto/package.dto";
