/**
 * PublicationHoldRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PublicationHoldRepository Port
 *
 * DDD: Application port for publicationholdrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListPublicationHoldsInput, ListPublicationHoldsOutput } from "../dto/publication-hold.dto";
export interface PublicationHoldRepository {
  listPublicationHolds(input: ListPublicationHoldsInput): Promise<ListPublicationHoldsOutput>;
}

export type { ListPublicationHoldsInput, ListPublicationHoldsOutput } from "../dto/publication-hold.dto";
