/**
 * Agreement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Agreement DTOs
 *
 * DDD: Application DTOs for Agreement use cases.
 */

import type { GetLabellerAgreementParams } from "@cutpoint/core/labelling/types";

export type GetLabellerAgreementInput = GetLabellerAgreementParams;

export type GetLabellerAgreementOutput = {};
