/**
 * Batch DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Batch DTOs
 *
 * DDD: Application DTOs for Batch use cases.
 */

import type { CreateAnnotationBatchRequestInput, ListAnnotationBatchesParams } from "@cutpoint/core/labelling/types";

export type ListAnnotationBatchesInput = ListAnnotationBatchesParams;

export type CreateAnnotationBatchInput = CreateAnnotationBatchRequestInput;

export type ListAnnotationBatchesOutput = {};

export type CreateAnnotationBatchOutput = {};
