/**
 * ClassificationRun DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClassificationRun DTOs
 *
 * DDD: Application DTOs for ClassificationRun use cases.
 */

import type { ListClassificationRunsParams } from "@cutpoint/core/labelling/types";

export type ListClassificationRunsInput = ListClassificationRunsParams;

export type ListClassificationRunsOutput = {};
