/**
 * Label DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Label DTOs
 *
 * DDD: Application DTOs for Label use cases.
 */

import type { SubmitAnnotationLabelsParams, SubmitAnnotationLabelsRequestInput } from "@cutpoint/core/labelling/types";

export type SubmitAnnotationLabelsInput = SubmitAnnotationLabelsParams & SubmitAnnotationLabelsRequestInput;

export type SubmitAnnotationLabelsOutput = {};
