/**
 * Taxonomy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Taxonomy DTOs
 *
 * DDD: Application DTOs for Taxonomy use cases.
 */

import type { GetTaxonomyParams } from "@cutpoint/core/labelling/types";

export type GetTaxonomyInput = GetTaxonomyParams;

export type GetTaxonomyOutput = {};
