/**
 * Version DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Version DTOs
 *
 * DDD: Application DTOs for Version use cases.
 */

import type { PublishTaxonomyVersionParams, PublishTaxonomyVersionRequestInput } from "@cutpoint/core/labelling/types";

export type PublishTaxonomyVersionInput = PublishTaxonomyVersionParams & PublishTaxonomyVersionRequestInput;

export type PublishTaxonomyVersionOutput = {};
