/**
 * ExecuteSealEvidencePackage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSealEvidencePackage Use Case
 *
 * DDD: Application use case for get Package.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SealEvidencePackageInput, SealEvidencePackageOutput } from "../dto/package.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { PackageRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteSealEvidencePackage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly packageRepo: PackageRepository
  ) {}

  async execute(input: SealEvidencePackageInput): Promise<SealEvidencePackageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: chainAdjudicationIds, purpose, recipient
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.packageRepo.sealEvidencePackage({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as SealEvidencePackageOutput;
  }
}
