/**
 * ExecuteGetEvidencePackage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetEvidencePackage Use Case
 *
 * DDD: Application use case for get Package.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetEvidencePackageInput, GetEvidencePackageOutput } from "../dto/package.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { PackageRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetEvidencePackage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly packageRepo: PackageRepository
  ) {}

  async execute(input: GetEvidencePackageInput): Promise<GetEvidencePackageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).packageId) {
      throw new ValidationError("packageId is required");
    }
    const packageId = (input as any).packageId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.packageRepo.getEvidencePackage({ packageId: packageId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${packageId}`);
    }

    return entity as GetEvidencePackageOutput;
  }
}
