/**
 * ExecuteListPublicationHolds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPublicationHolds Use Case
 *
 * DDD: Application use case for list PublicationHold.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPublicationHoldsInput, ListPublicationHoldsOutput } from "../dto/publication-hold.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { PublicationHoldRepository } from "../ports";

export class ExecuteListPublicationHolds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly publicationHold: PublicationHoldRepository
  ) {}

  async execute(input: ListPublicationHoldsInput): Promise<ListPublicationHoldsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.publicationHold.listPublicationHolds({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPublicationHoldsOutput;
  }
}
