/**
 * ListCandidate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListChainCandidatesParams } from "@cutpoint/core/discovery";

export function createListCandidateRequest(overrides: Partial<ListChainCandidatesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
