/**
 * ClassificationRun Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ClassificationRunEntity } from "@cutpoint/core/labelling/models/index.js";
import { labellingSchemas } from "@cutpoint/core/labelling";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "lbl";

export function createClassificationRun(overrides: Partial<ClassificationRunEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    classificationRunId: overrides.classificationRunId ?? `run_${ulid().toLowerCase()}`,
    completedAt: overrides.completedAt ?? new Date().toISOString(),
    marketId: overrides.marketId ?? `mkt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return labellingSchemas.ClassificationRun.parse(raw);
}

export function classificationRunBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createClassificationRun(overrides));
}
