/**
 * ExecuteIngestCorpus - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestCorpus Use Case
 *
 * DDD: Application use case for get Corpora.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestCorpusInput, IngestCorpusOutput } from "../dto/corpora.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { CorporaRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestCorpus {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly corpora: CorporaRepository
  ) {}

  async execute(input: IngestCorpusInput): Promise<IngestCorpusOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: coverageEnd, coverageStart, licence, payloadReference, pseudonymiseActors, retention
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).marketId) {
      throw new ValidationError("marketId is required");
    }
    const marketId = (input as any).marketId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.corpora.ingestCorpus({ marketId: marketId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${marketId}`);
    }

    return entity as IngestCorpusOutput;
  }
}
