/**
 * ExecuteListCorpora - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCorpora Use Case
 *
 * DDD: Application use case for list Corpora.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCorporaInput, ListCorporaOutput } from "../dto/corpora.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { CorporaRepository } from "../ports";

export class ExecuteListCorpora {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly corpora: CorporaRepository
  ) {}

  async execute(input: ListCorporaInput): Promise<ListCorporaOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.corpora.listCorpora({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCorporaOutput;
  }
}
