/**
 * ExecuteListMarkets - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMarkets Use Case
 *
 * DDD: Application use case for list Market.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMarketsInput, ListMarketsOutput } from "../dto/market.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { MarketRepository } from "../ports";

export class ExecuteListMarkets {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly market: MarketRepository
  ) {}

  async execute(input: ListMarketsInput): Promise<ListMarketsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.market.listMarkets({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMarketsOutput;
  }
}
