/**
 * AdjudicationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdjudicationRepository Port
 *
 * DDD: Application port for adjudicationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AdjudicateChainCandidateInput, AdjudicateChainCandidateOutput } from "../dto/adjudication.dto";
export interface AdjudicationRepository {
  adjudicateChainCandidate(input: AdjudicateChainCandidateInput): Promise<AdjudicateChainCandidateOutput>;
}

export type { AdjudicateChainCandidateInput, AdjudicateChainCandidateOutput } from "../dto/adjudication.dto";
