/**
 * CandidateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CandidateRepository Port
 *
 * DDD: Application port for candidaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetChainCandidateInput, GetChainCandidateOutput, ListChainCandidatesInput, ListChainCandidatesOutput } from "../dto/candidate.dto";
export interface CandidateRepository {
  listChainCandidates(input: ListChainCandidatesInput): Promise<ListChainCandidatesOutput>;
  getChainCandidate(input: GetChainCandidateInput): Promise<GetChainCandidateOutput>;
}

export type { GetChainCandidateInput, GetChainCandidateOutput, ListChainCandidatesInput, ListChainCandidatesOutput } from "../dto/candidate.dto";
