/**
 * DependencyMapRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DependencyMapRepository Port
 *
 * DDD: Application port for dependencymaprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDependencyMapInput, GetDependencyMapOutput } from "../dto/dependency-map.dto";
export interface DependencyMapRepository {
  getDependencyMap(input: GetDependencyMapInput): Promise<GetDependencyMapOutput>;
}

export type { GetDependencyMapInput, GetDependencyMapOutput } from "../dto/dependency-map.dto";
