/**
 * EdgeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EdgeRepository Port
 *
 * DDD: Application port for edgerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListDependencyEdgesInput, ListDependencyEdgesOutput } from "../dto/edge.dto";
export interface EdgeRepository {
  listDependencyEdges(input: ListDependencyEdgesInput): Promise<ListDependencyEdgesOutput>;
}

export type { ListDependencyEdgesInput, ListDependencyEdgesOutput } from "../dto/edge.dto";
