/**
 * ListCandidate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListInterventionCandidatesParams } from "@cutpoint/core/interventions";

export function createListCandidateRequest(overrides: Partial<ListInterventionCandidatesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
