/**
 * PublishTaxonomyVersion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { publishTaxonomyVersion } from "@cutpoint/api-server/domains/labelling/handlers";
import type { LabellingDDDDependencies } from "@cutpoint/api-server/domains/labelling";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { LABELLING_USE_CASES } from "../__factories__/use-cases.js";

describe("PublishTaxonomyVersion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LabellingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LabellingDDDDependencies>(
      LABELLING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePublishTaxonomyVersion, "execute").mockResolvedValue(useCaseResult);

    await publishTaxonomyVersion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePublishTaxonomyVersion.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
