/**
 * GetPackage DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetEvidencePackageParams } from "@cutpoint/core/governance";

export function createGetPackageRequest(overrides: Partial<GetEvidencePackageParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
