/**
 * Handlers for Agreement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LabellingDomainModule } from "../dependencies/labelling-ddd.dependencies.js";
import type { GetLabellerAgreementInput } from "@cutpoint/services/labelling";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/annotation/batches/{batchId}/agreement
 * Operation: getLabellerAgreement
 */
export async function getLabellerAgreement(
  request: FastifyRequest<{ Params: { batchId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LabellingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLabellerAgreementInput = {
    batchId: request.params.batchId,
  };
  const result = await deps.useCases.agreements.get.execute(input);
  return reply.code(200).send(result);
}


