/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./agreement.handlers.js";
export * from "./batch.handlers.js";
export * from "./classification-run.handlers.js";
export * from "./label.handlers.js";
export * from "./taxonomy.handlers.js";
export * from "./version.handlers.js";
