/**
 * Handlers for Label
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LabellingDomainModule } from "../dependencies/labelling-ddd.dependencies.js";
import type { SubmitAnnotationLabelsInput } from "@cutpoint/services/labelling";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/annotation/batches/{batchId}/labels
 * Operation: submitAnnotationLabels
 */
export async function submitAnnotationLabels(
  request: FastifyRequest<{ Params: { batchId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LabellingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitAnnotationLabelsInput = {
    batchId: request.params.batchId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.labels.create.execute(input);
  return reply.code(201).send(result);
}


