/**
 * CorporaRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorporaRepository Port
 *
 * DDD: Application port for corporarepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestCorpusInput, IngestCorpusOutput, ListCorporaInput, ListCorporaOutput } from "../dto/corpora.dto";
export interface CorporaRepository {
  listCorpora(input: ListCorporaInput): Promise<ListCorporaOutput>;
  ingestCorpus(input: IngestCorpusInput): Promise<IngestCorpusOutput>;
}

export type { IngestCorpusInput, IngestCorpusOutput, ListCorporaInput, ListCorporaOutput } from "../dto/corpora.dto";
