/**
 * MarketRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketRepository Port
 *
 * DDD: Application port for marketrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetMarketInput, GetMarketOutput, ListMarketsInput, ListMarketsOutput, RegisterMarketInput, RegisterMarketOutput } from "../dto/market.dto";
export interface MarketRepository {
  listMarkets(input: ListMarketsInput): Promise<ListMarketsOutput>;
  registerMarket(input: RegisterMarketInput): Promise<RegisterMarketOutput>;
  getMarket(input: GetMarketInput): Promise<GetMarketOutput>;
}

export type { GetMarketInput, GetMarketOutput, ListMarketsInput, ListMarketsOutput, RegisterMarketInput, RegisterMarketOutput } from "../dto/market.dto";
