/**
 * SealEvidencePackage handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { sealEvidencePackage } from "@cutpoint/api-server/domains/governance/handlers";
import type { GovernanceDDDDependencies } from "@cutpoint/api-server/domains/governance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { GOVERNANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("SealEvidencePackage", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GovernanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GovernanceDDDDependencies>(
      GOVERNANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSealEvidencePackage, "execute").mockResolvedValue(useCaseResult);

    await sealEvidencePackage(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSealEvidencePackage.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
