/**
 * Markets DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Markets Domain Module - Composition root
 *
 * DDD: Composition root for markets domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CorporaRepositoryAdapter,
  MarketRepositoryAdapter,
} from "@cutpoint/adapters/markets";
import { getIdGeneratorService } from "@cutpoint/adapters";
import type { AdapterDynamoDBClient } from "@cutpoint/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetMarket,
  ExecuteIngestCorpus,
  ExecuteListCorpora,
  ExecuteListMarkets,
  ExecuteRegisterMarket,
} from "@cutpoint/services/markets/usecases";
// Ports (interfaces)
import type {
  CorporaRepository,
  MarketRepository,
} from "@cutpoint/services/markets/ports";

export interface MarketsDomainModule {
  repos: {
    corporas: CorporaRepository;
    markets: MarketRepository;
  };
  useCases: {
    corporas: {
      get: ExecuteIngestCorpus;
      list: ExecuteListCorpora;
    };
    markets: {
      create: ExecuteRegisterMarket;
      get: ExecuteGetMarket;
      list: ExecuteListMarkets;
    };
  };
}

export function buildMarketsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MarketsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      corporas?: CorporaRepository;
      markets?: MarketRepository;
    } = {};

    obj.corporas = new CorporaRepositoryAdapter(dynamoClient);
    obj.markets = new MarketRepositoryAdapter(dynamoClient);
    return {
      corporas: obj.corporas!,
      markets: obj.markets!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    corporas: {
      get: new ExecuteIngestCorpus(executionContext, idGenerator, repos.corporas),
      list: new ExecuteListCorpora(executionContext, idGenerator, repos.corporas),
    },
    markets: {
      create: new ExecuteRegisterMarket(executionContext, idGenerator, repos.markets),
      get: new ExecuteGetMarket(executionContext, idGenerator, repos.markets),
      list: new ExecuteListMarkets(executionContext, idGenerator, repos.markets),
    },
  };
  return { repos, useCases: useCases as MarketsDomainModule["useCases"] };
}
