/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the labelling domain.
 * Use these factories in tests to create test data.
 */

export { createClassificationRun } from "./classification-run/entity/classification-run.entity.factory.js";
export { createTaxonomy } from "./taxonomy/entity/taxonomy.entity.factory.js";
