/**
 * Routes for Agreement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getLabellerAgreement } from "../handlers/agreement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function agreementRoutes(fastify: FastifyInstance) {
  // GET /v1/annotation/batches/{batchId}/agreement (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/annotation/batches/:batchId/agreement",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { batchId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLabellingDependenciesForRequest();
        await getLabellerAgreement(request, reply, deps);
      });
    }
  );


}
