/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { batchRoutes } from "./batch.routes.js";
export { classificationRunRoutes } from "./classification-run.routes.js";
export { agreementRoutes } from "./agreement.routes.js";
export { labelRoutes } from "./label.routes.js";
export { taxonomyRoutes } from "./taxonomy.routes.js";
export { versionRoutes } from "./version.routes.js";
