/**
 * Routes for Taxonomy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getTaxonomy } from "../handlers/taxonomy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function taxonomyRoutes(fastify: FastifyInstance) {
  // GET /v1/markets/{marketId}/taxonomy (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/markets/:marketId/taxonomy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLabellingDependenciesForRequest();
        await getTaxonomy(request, reply, deps);
      });
    }
  );


}
