/**
 * Routes for Version
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { publishTaxonomyVersion } from "../handlers/version.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function versionRoutes(fastify: FastifyInstance) {
  // POST /v1/markets/{marketId}/taxonomy/versions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/markets/:marketId/taxonomy/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLabellingDependenciesForRequest();
        await publishTaxonomyVersion(request, reply, deps);
      });
    }
  );


}
