/**
 * ListClassificationRuns handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listClassificationRuns } from "@cutpoint/api-server/domains/labelling/handlers";
import type { LabellingDDDDependencies } from "@cutpoint/api-server/domains/labelling";
import { createClassificationRun as createClassificationRunEntity } from "@cutpoint/factories/labelling";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { LABELLING_USE_CASES } from "../__factories__/use-cases.js";

describe("ListClassificationRuns", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LabellingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LabellingDDDDependencies>(
      LABELLING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createClassificationRunEntity({ orgId }),
      createClassificationRunEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListClassificationRuns, "execute").mockResolvedValue(useCaseResult);

    await listClassificationRuns(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListClassificationRuns.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
