/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/interventions/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List control-change candidates ranked by leverage */
        get: operations["listInterventionCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List interventions including declined and failed */
        get: operations["listInterventions"];
        put?: never;
        /** Select or decline a control-change candidate */
        post: operations["selectIntervention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interventions/{interventionId}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record outcome measurement against baseline */
        post: operations["recordInterventionOutcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MarketId: string;
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        InterventionCandidateId: string;
        InterventionCandidate: {
            interventionCandidateId: string;
            marketId: string;
            severedEdgeId: string;
            controlChange: string;
            /** @enum {string} */
            controlDomain?: "authentication" | "account_recovery" | "rate_limiting" | "payment_channel" | "listing_policy" | "carrier_process";
            /** Format: float */
            severanceLeverage?: number;
            /** Format: double */
            estimatedHarmSevered?: number;
            harmMetric?: string;
            /** @enum {string} */
            implementationDifficulty?: "low" | "medium" | "high";
            supportingChainCount?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InterventionCandidateListData: {
            items: {
                interventionCandidateId: string;
                marketId: string;
                severedEdgeId: string;
                controlChange: string;
                /** @enum {string} */
                controlDomain?: "authentication" | "account_recovery" | "rate_limiting" | "payment_channel" | "listing_policy" | "carrier_process";
                /** Format: float */
                severanceLeverage?: number;
                /** Format: double */
                estimatedHarmSevered?: number;
                harmMetric?: string;
                /** @enum {string} */
                implementationDifficulty?: "low" | "medium" | "high";
                supportingChainCount?: number;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        InterventionCandidateListResponse: {
            data: {
                items: {
                    interventionCandidateId: string;
                    marketId: string;
                    severedEdgeId: string;
                    controlChange: string;
                    /** @enum {string} */
                    controlDomain?: "authentication" | "account_recovery" | "rate_limiting" | "payment_channel" | "listing_policy" | "carrier_process";
                    /** Format: float */
                    severanceLeverage?: number;
                    /** Format: double */
                    estimatedHarmSevered?: number;
                    harmMetric?: string;
                    /** @enum {string} */
                    implementationDifficulty?: "low" | "medium" | "high";
                    supportingChainCount?: number;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        InterventionId: string;
        HarmBaseline: {
            harmMetric: string;
            /** Format: double */
            value: number;
            /** @example accounts_per_month */
            unit?: string;
            /** Format: date */
            windowStart: string;
            /** Format: date */
            windowEnd: string;
            sourceSystem?: string;
        };
        Intervention: {
            interventionId: string;
            candidateId: string;
            /** @enum {string} */
            status: "selected" | "declined" | "implemented" | "measured" | "failed";
            declineReason?: string;
            ownerTeam?: string;
            changeRecordReference?: string;
            hypothesis?: string;
            baseline?: {
                harmMetric: string;
                /** Format: double */
                value: number;
                /** @example accounts_per_month */
                unit?: string;
                /** Format: date */
                windowStart: string;
                /** Format: date */
                windowEnd: string;
                sourceSystem?: string;
            };
            /** Format: date-time */
            measurementDueAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InterventionListData: {
            items: {
                interventionId: string;
                candidateId: string;
                /** @enum {string} */
                status: "selected" | "declined" | "implemented" | "measured" | "failed";
                declineReason?: string;
                ownerTeam?: string;
                changeRecordReference?: string;
                hypothesis?: string;
                baseline?: {
                    harmMetric: string;
                    /** Format: double */
                    value: number;
                    /** @example accounts_per_month */
                    unit?: string;
                    /** Format: date */
                    windowStart: string;
                    /** Format: date */
                    windowEnd: string;
                    sourceSystem?: string;
                };
                /** Format: date-time */
                measurementDueAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        InterventionListResponse: {
            data: {
                items: {
                    interventionId: string;
                    candidateId: string;
                    /** @enum {string} */
                    status: "selected" | "declined" | "implemented" | "measured" | "failed";
                    declineReason?: string;
                    ownerTeam?: string;
                    changeRecordReference?: string;
                    hypothesis?: string;
                    baseline?: {
                        harmMetric: string;
                        /** Format: double */
                        value: number;
                        /** @example accounts_per_month */
                        unit?: string;
                        /** Format: date */
                        windowStart: string;
                        /** Format: date */
                        windowEnd: string;
                        sourceSystem?: string;
                    };
                    /** Format: date-time */
                    measurementDueAt?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        InterventionCreate: {
            candidateId: string;
            /** @enum {string} */
            decision: "select" | "decline";
            declineReason?: string;
            ownerTeam?: string;
            hypothesis?: string;
            /** @default 90 */
            measurementWindowDays: number;
        };
        InterventionResponse: {
            data: {
                interventionId: string;
                candidateId: string;
                /** @enum {string} */
                status: "selected" | "declined" | "implemented" | "measured" | "failed";
                declineReason?: string;
                ownerTeam?: string;
                changeRecordReference?: string;
                hypothesis?: string;
                baseline?: {
                    harmMetric: string;
                    /** Format: double */
                    value: number;
                    /** @example accounts_per_month */
                    unit?: string;
                    /** Format: date */
                    windowStart: string;
                    /** Format: date */
                    windowEnd: string;
                    sourceSystem?: string;
                };
                /** Format: date-time */
                measurementDueAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        OutcomeMeasurementCreate: {
            harmMetric: string;
            /** Format: double */
            value: number;
            /** Format: date */
            windowStart: string;
            /** Format: date */
            windowEnd: string;
            substitutionObserved?: boolean;
            notes?: string;
        };
        OutcomeMeasurementId: string;
        OutcomeMeasurement: {
            outcomeMeasurementId: string;
            interventionId: string;
            harmMetric: string;
            /** Format: double */
            value: number;
            /** Format: double */
            baselineValue?: number;
            /** Format: double */
            harmSevered?: number;
            movedTargetMetric?: boolean;
            substitutionObserved?: boolean;
            /** Format: date-time */
            measuredAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OutcomeMeasurementResponse: {
            data: {
                outcomeMeasurementId: string;
                interventionId: string;
                harmMetric: string;
                /** Format: double */
                value: number;
                /** Format: double */
                baselineValue?: number;
                /** Format: double */
                harmSevered?: number;
                movedTargetMetric?: boolean;
                substitutionObserved?: boolean;
                /** Format: date-time */
                measuredAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listInterventionCandidates: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                marketId?: string;
                harmMetric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intervention candidates page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                interventionCandidateId: string;
                                marketId: string;
                                severedEdgeId: string;
                                controlChange: string;
                                /** @enum {string} */
                                controlDomain?: "authentication" | "account_recovery" | "rate_limiting" | "payment_channel" | "listing_policy" | "carrier_process";
                                /** Format: float */
                                severanceLeverage?: number;
                                /** Format: double */
                                estimatedHarmSevered?: number;
                                harmMetric?: string;
                                /** @enum {string} */
                                implementationDifficulty?: "low" | "medium" | "high";
                                supportingChainCount?: number;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listInterventions: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                status?: "selected" | "declined" | "implemented" | "measured" | "failed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interventions page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                interventionId: string;
                                candidateId: string;
                                /** @enum {string} */
                                status: "selected" | "declined" | "implemented" | "measured" | "failed";
                                declineReason?: string;
                                ownerTeam?: string;
                                changeRecordReference?: string;
                                hypothesis?: string;
                                baseline?: {
                                    harmMetric: string;
                                    /** Format: double */
                                    value: number;
                                    /** @example accounts_per_month */
                                    unit?: string;
                                    /** Format: date */
                                    windowStart: string;
                                    /** Format: date */
                                    windowEnd: string;
                                    sourceSystem?: string;
                                };
                                /** Format: date-time */
                                measurementDueAt?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    selectIntervention: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    candidateId: string;
                    /** @enum {string} */
                    decision: "select" | "decline";
                    declineReason?: string;
                    ownerTeam?: string;
                    hypothesis?: string;
                    /** @default 90 */
                    measurementWindowDays?: number;
                };
            };
        };
        responses: {
            /** @description Intervention recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            interventionId: string;
                            candidateId: string;
                            /** @enum {string} */
                            status: "selected" | "declined" | "implemented" | "measured" | "failed";
                            declineReason?: string;
                            ownerTeam?: string;
                            changeRecordReference?: string;
                            hypothesis?: string;
                            baseline?: {
                                harmMetric: string;
                                /** Format: double */
                                value: number;
                                /** @example accounts_per_month */
                                unit?: string;
                                /** Format: date */
                                windowStart: string;
                                /** Format: date */
                                windowEnd: string;
                                sourceSystem?: string;
                            };
                            /** Format: date-time */
                            measurementDueAt?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recordInterventionOutcome: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                interventionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    harmMetric: string;
                    /** Format: double */
                    value: number;
                    /** Format: date */
                    windowStart: string;
                    /** Format: date */
                    windowEnd: string;
                    substitutionObserved?: boolean;
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Outcome measured */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            outcomeMeasurementId: string;
                            interventionId: string;
                            harmMetric: string;
                            /** Format: double */
                            value: number;
                            /** Format: double */
                            baselineValue?: number;
                            /** Format: double */
                            harmSevered?: number;
                            movedTargetMetric?: boolean;
                            substitutionObserved?: boolean;
                            /** Format: date-time */
                            measuredAt?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
