/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildDiscoveryDomainModule } from "./discovery/dependencies/discovery-ddd.dependencies.js";
export { buildGovernanceDomainModule } from "./governance/dependencies/governance-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildInterventionsDomainModule } from "./interventions/dependencies/interventions-ddd.dependencies.js";
export { buildLabellingDomainModule } from "./labelling/dependencies/labelling-ddd.dependencies.js";
export { buildMarketsDomainModule } from "./markets/dependencies/markets-ddd.dependencies.js";

// Export all domain dependency types
export type { DiscoveryDomainModule } from "./discovery/dependencies/discovery-ddd.dependencies.js";
export type { GovernanceDomainModule } from "./governance/dependencies/governance-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { InterventionsDomainModule } from "./interventions/dependencies/interventions-ddd.dependencies.js";
export type { LabellingDomainModule } from "./labelling/dependencies/labelling-ddd.dependencies.js";
export type { MarketsDomainModule } from "./markets/dependencies/markets-ddd.dependencies.js";
