/**
 * Labelling DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Labelling Domain Module - Composition root
 *
 * DDD: Composition root for labelling domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AgreementRepositoryAdapter,
  BatchRepositoryAdapter,
  ClassificationRunRepositoryAdapter,
  LabelRepositoryAdapter,
  TaxonomyRepositoryAdapter,
} from "@cutpoint/adapters/labelling";
import { getIdGeneratorService } from "@cutpoint/adapters";
import type { AdapterDynamoDBClient } from "@cutpoint/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAnnotationBatch,
  ExecuteGetTaxonomy,
  ExecuteListAnnotationBatches,
  ExecuteListClassificationRuns,
  ExecutePublishTaxonomyVersion,
  ExecuteSubmitAnnotationLabels,
} from "@cutpoint/services/labelling/usecases";
// Ports (interfaces)
import type {
  AgreementRepository,
  BatchRepository,
  ClassificationRunRepository,
  LabelRepository,
  TaxonomyRepository,
} from "@cutpoint/services/labelling/ports";

export interface LabellingDomainModule {
  repos: {
    agreements: AgreementRepository;
    batches: BatchRepository;
    classificationRuns: ClassificationRunRepository;
    labels: LabelRepository;
    taxonomies: TaxonomyRepository;
  };
  useCases: {
    batches: {
      create: ExecuteCreateAnnotationBatch;
      list: ExecuteListAnnotationBatches;
    };
    classificationRuns: {
      list: ExecuteListClassificationRuns;
    };
    labels: {
      create: ExecuteSubmitAnnotationLabels;
    };
    taxonomies: {
      get: ExecuteGetTaxonomy;
    };
  };
}

export function buildLabellingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): LabellingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      agreements?: AgreementRepository;
      batches?: BatchRepository;
      classificationRuns?: ClassificationRunRepository;
      labels?: LabelRepository;
      taxonomies?: TaxonomyRepository;
    } = {};

    obj.agreements = new AgreementRepositoryAdapter(dynamoClient);
    obj.batches = new BatchRepositoryAdapter(dynamoClient);
    obj.classificationRuns = new ClassificationRunRepositoryAdapter(dynamoClient);
    obj.labels = new LabelRepositoryAdapter(dynamoClient);
    obj.taxonomies = new TaxonomyRepositoryAdapter(dynamoClient);
    return {
      agreements: obj.agreements!,
      batches: obj.batches!,
      classificationRuns: obj.classificationRuns!,
      labels: obj.labels!,
      taxonomies: obj.taxonomies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    batches: {
      create: new ExecuteCreateAnnotationBatch(executionContext, idGenerator, repos.batches),
      list: new ExecuteListAnnotationBatches(executionContext, idGenerator, repos.batches),
    },
    classificationRuns: {
      list: new ExecuteListClassificationRuns(executionContext, idGenerator, repos.classificationRuns),
    },
    labels: {
      create: new ExecuteSubmitAnnotationLabels(executionContext, idGenerator, repos.labels),
    },
    taxonomies: {
      get: new ExecuteGetTaxonomy(executionContext, idGenerator, repos.taxonomies),
    },
  };
  return { repos, useCases: useCases as LabellingDomainModule["useCases"] };
}
