/**
 * ExecuteListInterventions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListInterventions Use Case
 *
 * DDD: Application use case for list Intervention.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListInterventionsInput, ListInterventionsOutput } from "../dto/intervention.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { InterventionRepository } from "../ports";

export class ExecuteListInterventions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly intervention: InterventionRepository
  ) {}

  async execute(input: ListInterventionsInput): Promise<ListInterventionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.itvId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.intervention.listInterventions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListInterventionsOutput;
  }
}
