/**
 * Repository interface for Market
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  MarketEntity
} from "../models/market.entity.js";
import type {
  ListMarketsParams,
  Market
} from "../types/index.js";
/**
 * MarketRepository Interface
 */
export interface MarketRepository extends CreateReadRepository<MarketEntity, Market, string, ListMarketsParams> {

}
