/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./agreement/index.js";
export * from "./batch/index.js";
export * from "./classification-run/index.js";
export * from "./label/index.js";
export * from "./taxonomy/index.js";
export * from "./version/index.js";
