/**
 * Taxonomy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TaxonomyEntity } from "@cutpoint/core/labelling/models/index.js";
import { labellingSchemas } from "@cutpoint/core/labelling";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "lbl";

export function createTaxonomy(overrides: Partial<TaxonomyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    activeVersion: overrides.activeVersion ?? faker.lorem.word(),
    categories: overrides.categories ?? [],
    marketId: overrides.marketId ?? `mkt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return labellingSchemas.Taxonomy.parse(raw);
}

export function taxonomyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTaxonomy(overrides));
}
