/**
 * Repository interface for ClassificationRun
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ClassificationRunEntity
} from "../models/classification-run.entity.js";
import type {
  ListClassificationRunsParams
} from "../types/index.js";
/**
 * ClassificationRunRepository Interface
 */
export interface ClassificationRunRepository extends ReadRepository<ClassificationRunEntity, string, ListClassificationRunsParams> {

}
