/**
 * Repository interface for Taxonomy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TaxonomyEntity
} from "../models/taxonomy.entity.js";
/**
 * TaxonomyRepository Interface
 */
export interface TaxonomyRepository extends ReadRepository<TaxonomyEntity, string, Record<string, never>> {

}
