/**
 * ListClassificationRun DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListClassificationRunsParams } from "@cutpoint/core/labelling";

export function createListClassificationRunRequest(overrides: Partial<ListClassificationRunsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
