/**
 * CorporaRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorporaRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CorporaRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CorporaRepository,
} from "@cutpoint/services/markets";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CorporaRepositoryDdb } from "./corpora-repository.ddb.js";

/**
 * CorporaRepositoryAdapter
 *
 * Implements CorporaRepository port for infrastructure layer.
 */
export class CorporaRepositoryAdapter implements CorporaRepository {
  private readonly ddb: CorporaRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CorporaRepositoryDdb(this.dynamoClient);
  }

  async listCorpora(input: Parameters<CorporaRepository['listCorpora']>[0]): Promise<Awaited<ReturnType<CorporaRepository['listCorpora']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCorpora(input);
  }

  async ingestCorpus(input: Parameters<CorporaRepository['ingestCorpus']>[0]): Promise<Awaited<ReturnType<CorporaRepository['ingestCorpus']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestCorpus(input);
  }
}
