/**
 * MarketRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements MarketRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  MarketRepository,
} from "@cutpoint/services/markets";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { MarketRepositoryDdb } from "./market-repository.ddb.js";

/**
 * MarketRepositoryAdapter
 *
 * Implements MarketRepository port for infrastructure layer.
 */
export class MarketRepositoryAdapter implements MarketRepository {
  private readonly ddb: MarketRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new MarketRepositoryDdb(this.dynamoClient);
  }

  async listMarkets(input: Parameters<MarketRepository['listMarkets']>[0]): Promise<Awaited<ReturnType<MarketRepository['listMarkets']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listMarkets(input);
  }

  async registerMarket(input: Parameters<MarketRepository['registerMarket']>[0]): Promise<Awaited<ReturnType<MarketRepository['registerMarket']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerMarket(input);
  }

  async getMarket(input: Parameters<MarketRepository['getMarket']>[0]): Promise<Awaited<ReturnType<MarketRepository['getMarket']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getMarket(input);
  }
}
