/**
 * Routes for Coverage
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCoverageAssessment } from "../handlers/coverage.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function coverageRoutes(fastify: FastifyInstance) {
  // GET /v1/assurance/markets/{marketId}/coverage (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/assurance/markets/:marketId/coverage",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await getCoverageAssessment(request, reply, deps);
      });
    }
  );


}
