/**
 * Routes for Package
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getEvidencePackage, sealEvidencePackage } from "../handlers/package.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function packageRoutes(fastify: FastifyInstance) {
  // POST /v1/evidence/packages (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence/packages",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await sealEvidencePackage(request, reply, deps);
      });
    }
  );


  // GET /v1/evidence/packages/{packageId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence/packages/:packageId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { packageId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await getEvidencePackage(request, reply, deps);
      });
    }
  );


}
