/**
 * AgreementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AgreementRepository Port
 *
 * DDD: Application port for agreementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLabellerAgreementInput, GetLabellerAgreementOutput } from "../dto/agreement.dto";
export interface AgreementRepository {
  getLabellerAgreement(input: GetLabellerAgreementInput): Promise<GetLabellerAgreementOutput>;
}

export type { GetLabellerAgreementInput, GetLabellerAgreementOutput } from "../dto/agreement.dto";
