/**
 * LabelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LabelRepository Port
 *
 * DDD: Application port for labelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SubmitAnnotationLabelsInput, SubmitAnnotationLabelsOutput } from "../dto/label.dto";
export interface LabelRepository {
  submitAnnotationLabels(input: SubmitAnnotationLabelsInput): Promise<SubmitAnnotationLabelsOutput>;
}

export type { SubmitAnnotationLabelsInput, SubmitAnnotationLabelsOutput } from "../dto/label.dto";
