/**
 * TaxonomyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TaxonomyRepository Port
 *
 * DDD: Application port for taxonomyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTaxonomyInput, GetTaxonomyOutput } from "../dto/taxonomy.dto";
export interface TaxonomyRepository {
  getTaxonomy(input: GetTaxonomyInput): Promise<GetTaxonomyOutput>;
}

export type { GetTaxonomyInput, GetTaxonomyOutput } from "../dto/taxonomy.dto";
