/**
 * VersionPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VersionPublisher Port
 *
 * DDD: Application port for versionpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishTaxonomyVersionInput, PublishTaxonomyVersionOutput } from "../dto/version.dto";
export interface VersionPublisher {
  publishTaxonomyVersion(input: PublishTaxonomyVersionInput): Promise<PublishTaxonomyVersionOutput>;
}

export type { PublishTaxonomyVersionInput, PublishTaxonomyVersionOutput } from "../dto/version.dto";
