/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Discovery Domain Use Cases
 * 
 * List of all use case names for the discovery domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DISCOVERY_USE_CASES = [
  "executeAdjudicateChainCandidate",
  "executeGetChainCandidate",
  "executeGetDependencyMap",
  "executeListChainCandidates",
  "executeListDependencyEdges"
] as const;
