/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./candidate-repository.ddb.js";
export * from "./intervention-repository.ddb.js";
export * from "./outcome-repository.ddb.js";
export * from "./candidate-repository.adapter.js";
export * from "./intervention-repository.adapter.js";
export * from "./outcome-repository.adapter.js";
