/**
 * InterventionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InterventionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InterventionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InterventionRepository,
} from "@cutpoint/services/interventions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InterventionRepositoryDdb } from "./intervention-repository.ddb.js";

/**
 * InterventionRepositoryAdapter
 *
 * Implements InterventionRepository port for infrastructure layer.
 */
export class InterventionRepositoryAdapter implements InterventionRepository {
  private readonly ddb: InterventionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InterventionRepositoryDdb(this.dynamoClient);
  }

  async listInterventions(input: Parameters<InterventionRepository['listInterventions']>[0]): Promise<Awaited<ReturnType<InterventionRepository['listInterventions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listInterventions(input);
  }

  async selectIntervention(input: Parameters<InterventionRepository['selectIntervention']>[0]): Promise<Awaited<ReturnType<InterventionRepository['selectIntervention']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.selectIntervention(input);
  }
}
