/**
 * InterventionRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InterventionRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing Intervention repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { InterventionRepository } from "@cutpoint/services/interventions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * InterventionRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: INTERVENTION
 * Entity Token: INTERVENTION
 * SK Prefix: INTERVENTION
 */
export class InterventionRepositoryDdb implements InterventionRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "INTERVENTION";
  private readonly ENTITY_TOKEN = "INTERVENTION";
  private readonly SK_PREFIX = "INTERVENTION";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "INTERVENTIONS";
  private readonly ENTITY_TYPE_PK = "INTERVENTIONS";
  private generateCorrelationId(): string {
    const domainPrefix = "itv";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async listInterventions(input: Parameters<InterventionRepository['listInterventions']>[0]): Promise<Awaited<ReturnType<InterventionRepository['listInterventions']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const prefix = this.getCollectionPK(inputExt.orgId as string);
    const rawLimit = inputExt?.limit;
    const parsedLimit = rawLimit == null || rawLimit === ""
      ? 50
      : (typeof rawLimit === "string" ? parseInt(rawLimit as string, 10) : Number(rawLimit));
    const limit = Number.isFinite(parsedLimit) && parsedLimit > 0 ? parsedLimit : 50;
    const result = await this.dynamoClient.scan({
      TableName: this.TABLE_NAME,
      FilterExpression: "begins_with(PK, :prefix)",
      ExpressionAttributeValues: { ":prefix": prefix },
      Limit: limit,
      ...((() => {
        const c = inputExt?.cursor;
        if (!c || (typeof c === "string" && !c.trim())) return {};
        try {
          return {
            ExclusiveStartKey: typeof c === "string"
              ? JSON.parse(Buffer.from(c, "base64").toString())
              : c,
          };
        } catch {
          return {};
        }
      })()),
    });
    const items = ((result.Items || []) as Record<string, unknown>[]).map((i) => sanitizeItem(i));
    return {
      data: { items: items } as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
        pagination: {
          nextCursor: result.LastEvaluatedKey ? Buffer.from(JSON.stringify(result.LastEvaluatedKey)).toString("base64") : null,
          prevCursor: null,
          limit: inputExt?.limit || 50,
        },
      } as unknown as any,
    };
  }

  async selectIntervention(input: Parameters<InterventionRepository['selectIntervention']>[0]): Promise<Awaited<ReturnType<InterventionRepository['selectIntervention']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!(inputExt.interventionId ?? inputExt.id ?? inputExt.interventionId)) {
      throw new Error("Missing required parameter: interventionId");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, (inputExt.interventionId ?? inputExt.id ?? inputExt.interventionId) as string);
    // Soft-delete layout prefixes SK with ACTIVE# when statusPrefix is enabled.
    const skPrefix = `${this.ENTITY_TOKEN}#${(inputExt.interventionId ?? inputExt.id ?? inputExt.interventionId)}#`;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": skPrefix },
      Limit: 1,
    });
    const item = result.Items?.[0];
    if (!item) {
      throw new Error(`${this.ENTITY_TYPE} with id ${(inputExt.interventionId ?? inputExt.id ?? inputExt.interventionId)} not found`);
    }
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
