/**
 * ExecuteListDependencyEdges - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDependencyEdges Use Case
 *
 * DDD: Application use case for list Edge.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDependencyEdgesInput, ListDependencyEdgesOutput } from "../dto/edge.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { EdgeRepository } from "../ports";

export class ExecuteListDependencyEdges {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly edge: EdgeRepository
  ) {}

  async execute(input: ListDependencyEdgesInput): Promise<ListDependencyEdgesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dscId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.edge.listDependencyEdges({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDependencyEdgesOutput;
  }
}
