/**
 * ExecuteAdjudicateChainCandidate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAdjudicateChainCandidate Use Case
 *
 * DDD: Application use case for get Adjudication.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AdjudicateChainCandidateInput, AdjudicateChainCandidateOutput } from "../dto/adjudication.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cutpoint/services/_shared/index.js";
import type { AdjudicationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAdjudicateChainCandidate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly adjudication: AdjudicationRepository
  ) {}

  async execute(input: AdjudicateChainCandidateInput): Promise<AdjudicateChainCandidateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dscId();

    // All field names extracted from OpenAPI spec: harmMetric, outcome, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).candidateId) {
      throw new ValidationError("candidateId is required");
    }
    const candidateId = (input as any).candidateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.adjudication.adjudicateChainCandidate({ candidateId: candidateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${candidateId}`);
    }

    return entity as AdjudicateChainCandidateOutput;
  }
}
