/**
 * Routes for Adjudication
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { adjudicateChainCandidate } from "../handlers/adjudication.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function adjudicationRoutes(fastify: FastifyInstance) {
  // POST /v1/chains/candidates/{candidateId}/adjudication (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/chains/candidates/:candidateId/adjudication",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDiscoveryDependenciesForRequest();
        await adjudicateChainCandidate(request, reply, deps);
      });
    }
  );


}
