/**
 * Routes for Edge
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listDependencyEdges } from "../handlers/edge.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function edgeRoutes(fastify: FastifyInstance) {
  // GET /v1/dependencies/edges (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/dependencies/edges",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDiscoveryDependenciesForRequest();
        await listDependencyEdges(request, reply, deps);
      });
    }
  );


}
