/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { edgeRoutes } from "./edge.routes.js";
export { adjudicationRoutes } from "./adjudication.routes.js";
export { candidateRoutes } from "./candidate.routes.js";
export { dependencyMapRoutes } from "./dependency-map.routes.js";
