/**
 * Candidate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Candidate DTOs
 *
 * DDD: Application DTOs for Candidate use cases.
 */

import type { ListInterventionCandidatesParams } from "@cutpoint/core/interventions/types";

export type ListInterventionCandidatesInput = ListInterventionCandidatesParams;

export type ListInterventionCandidatesOutput = {};
