/**
 * Intervention DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Intervention DTOs
 *
 * DDD: Application DTOs for Intervention use cases.
 */

import type { ListInterventionsParams, SelectInterventionRequestInput } from "@cutpoint/core/interventions/types";

export type ListInterventionsInput = ListInterventionsParams;

export type SelectInterventionInput = SelectInterventionRequestInput;

export type ListInterventionsOutput = {};

export type SelectInterventionOutput = {};
