/**
 * Outcome DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Outcome DTOs
 *
 * DDD: Application DTOs for Outcome use cases.
 */

import type { RecordInterventionOutcomeParams, RecordInterventionOutcomeRequestInput } from "@cutpoint/core/interventions/types";

export type RecordInterventionOutcomeInput = RecordInterventionOutcomeParams & RecordInterventionOutcomeRequestInput;

export type RecordInterventionOutcomeOutput = {};
