/**
 * GetTaxonomy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: labelling
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetTaxonomyParams } from "@cutpoint/core/labelling";

export function createGetTaxonomyRequest(overrides: Partial<GetTaxonomyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
