/**
 * Intervention Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/interventions.openapi.types.js";
import { schemas } from "../schemas/interventions.schemas.js";

/**
 * Entity: InterventionEntity
 * Description: Represents the Intervention domain model.
 * Source: schemas.Intervention
 * Type: Domain Entity (API)
 */
export const InterventionEntitySchema = schemas.Intervention;
export type InterventionEntity = components["schemas"]["Intervention"];
