/**
 * Routes for Corpora
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { ingestCorpus, listCorpora } from "../handlers/corpora.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function corporaRoutes(fastify: FastifyInstance) {
  // POST /v1/markets/{marketId}/corpora (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/markets/:marketId/corpora",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketsDependenciesForRequest();
        await ingestCorpus(request, reply, deps);
      });
    }
  );


  // GET /v1/markets/{marketId}/corpora (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/markets/:marketId/corpora",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketsDependenciesForRequest();
        await listCorpora(request, reply, deps);
      });
    }
  );


}
