/**
 * Routes for Market
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getMarket, listMarkets, registerMarket } from "../handlers/market.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function marketRoutes(fastify: FastifyInstance) {
  // GET /v1/markets (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/markets",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketsDependenciesForRequest();
        await listMarkets(request, reply, deps);
      });
    }
  );


  // POST /v1/markets (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/markets",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketsDependenciesForRequest();
        await registerMarket(request, reply, deps);
      });
    }
  );


  // GET /v1/markets/{marketId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/markets/:marketId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketsDependenciesForRequest();
        await getMarket(request, reply, deps);
      });
    }
  );


}
