/**
 * Handlers for Candidate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DiscoveryDomainModule } from "../dependencies/discovery-ddd.dependencies.js";
import type { GetChainCandidateInput, ListChainCandidatesInput } from "@cutpoint/services/discovery";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/chains/candidates
 * Operation: listChainCandidates
 */
export async function listChainCandidates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], marketId?: string | string[], sourceCategory?: string | string[], destinationCategory?: string | string[], adjudicationStatus?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DiscoveryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListChainCandidatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.candidates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/chains/candidates/{candidateId}
 * Operation: getChainCandidate
 */
export async function getChainCandidate(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DiscoveryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetChainCandidateInput = {
    candidateId: request.params.candidateId,
  };
  const result = await deps.useCases.candidates.get.execute(input);
  return reply.code(200).send(result);
}


