/**
 * Handlers for DependencyMap
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DiscoveryDomainModule } from "../dependencies/discovery-ddd.dependencies.js";
import type { GetDependencyMapInput } from "@cutpoint/services/discovery";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/markets/{marketId}/dependency-map
 * Operation: getDependencyMap
 */
export async function getDependencyMap(
  request: FastifyRequest<{ Params: { marketId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DiscoveryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDependencyMapInput = {
    marketId: request.params.marketId,
  };
  const result = await deps.useCases.dependencyMaps.get.execute(input);
  return reply.code(200).send(result);
}


