/**
 * Handlers for Edge
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: discovery
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DiscoveryDomainModule } from "../dependencies/discovery-ddd.dependencies.js";
import type { ListDependencyEdgesInput } from "@cutpoint/services/discovery";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/dependencies/edges
 * Operation: listDependencyEdges
 */
export async function listDependencyEdges(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], marketId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DiscoveryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDependencyEdgesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.edges.list.execute(input);
  return reply.code(200).send(result);
}


