/**
 * Market Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/markets.openapi.types.js";
import { schemas } from "../schemas/markets.schemas.js";

/**
 * Entity: MarketEntity
 * Description: Represents the Market domain model.
 * Source: schemas.Market
 * Type: Domain Entity (API)
 */
export const MarketEntitySchema = schemas.Market;
export type MarketEntity = components["schemas"]["Market"];
