/**
 * Intervention Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { InterventionEntity } from "@cutpoint/core/interventions/models/index.js";
import { interventionsSchemas } from "@cutpoint/core/interventions";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "itv";

export function createIntervention(overrides: Partial<InterventionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    candidateId: overrides.candidateId ?? `icd_${ulid().toLowerCase()}`,
    interventionId: overrides.interventionId ?? `int_${ulid().toLowerCase()}`,
    status: overrides.status ?? "selected",
    ...overrides,
  };

  return interventionsSchemas.Intervention.parse(raw);
}

export function interventionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIntervention(overrides));
}
