/**
 * Market Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MarketEntity } from "@cutpoint/core/markets/models/index.js";
import { marketsSchemas } from "@cutpoint/core/markets";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mkt";

export function createMarket(overrides: Partial<MarketEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    language: overrides.language ?? faker.lorem.word(),
    marketId: overrides.marketId ?? `mkt_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "onboarding",
    ...overrides,
  };

  return marketsSchemas.Market.parse(raw);
}

export function marketBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMarket(overrides));
}
