/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: interventions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Interventions Domain Use Cases
 * 
 * List of all use case names for the interventions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const INTERVENTIONS_USE_CASES = [
  "executeListInterventionCandidates",
  "executeListInterventions",
  "executeRecordInterventionOutcome",
  "executeSelectIntervention"
] as const;
