/**
 * GetMarket handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getMarket } from "@cutpoint/api-server/domains/markets/handlers";
import type { MarketsDDDDependencies } from "@cutpoint/api-server/domains/markets";
import { createMarket as createMarketEntity } from "@cutpoint/factories/markets";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { MARKETS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetMarket", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MarketsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MarketsDDDDependencies>(
      MARKETS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createMarketEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetMarket, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { marketId: entity.id };

    await getMarket(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetMarket.execute).toHaveBeenCalledWith(expect.objectContaining({ marketId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { marketId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetMarket, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getMarket(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
