/**
 * ListMarkets handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listMarkets } from "@cutpoint/api-server/domains/markets/handlers";
import type { MarketsDDDDependencies } from "@cutpoint/api-server/domains/markets";
import { createMarket as createMarketEntity } from "@cutpoint/factories/markets";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cutpoint/tests/shared";
import { MARKETS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListMarkets", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MarketsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MarketsDDDDependencies>(
      MARKETS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createMarketEntity({ orgId }),
      createMarketEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListMarkets, "execute").mockResolvedValue(useCaseResult);

    await listMarkets(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListMarkets.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
