/**
 * CoverageRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CoverageRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CoverageRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CoverageRepository,
} from "@cutpoint/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CoverageRepositoryDdb } from "./coverage-repository.ddb.js";

/**
 * CoverageRepositoryAdapter
 *
 * Implements CoverageRepository port for infrastructure layer.
 */
export class CoverageRepositoryAdapter implements CoverageRepository {
  private readonly ddb: CoverageRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CoverageRepositoryDdb(this.dynamoClient);
  }

  async getCoverageAssessment(input: Parameters<CoverageRepository['getCoverageAssessment']>[0]): Promise<Awaited<ReturnType<CoverageRepository['getCoverageAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCoverageAssessment(input);
  }
}
