/**
 * DriftRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DriftRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DriftRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DriftRepository,
} from "@cutpoint/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DriftRepositoryDdb } from "./drift-repository.ddb.js";

/**
 * DriftRepositoryAdapter
 *
 * Implements DriftRepository port for infrastructure layer.
 */
export class DriftRepositoryAdapter implements DriftRepository {
  private readonly ddb: DriftRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DriftRepositoryDdb(this.dynamoClient);
  }

  async getDriftAssessment(input: Parameters<DriftRepository['getDriftAssessment']>[0]): Promise<Awaited<ReturnType<DriftRepository['getDriftAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDriftAssessment(input);
  }
}
