/**
 * PackageRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PackageRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PackageRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PackageRepository,
} from "@cutpoint/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PackageRepositoryDdb } from "./package-repository.ddb.js";

/**
 * PackageRepositoryAdapter
 *
 * Implements PackageRepository port for infrastructure layer.
 */
export class PackageRepositoryAdapter implements PackageRepository {
  private readonly ddb: PackageRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PackageRepositoryDdb(this.dynamoClient);
  }

  async sealEvidencePackage(input: Parameters<PackageRepository['sealEvidencePackage']>[0]): Promise<Awaited<ReturnType<PackageRepository['sealEvidencePackage']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.sealEvidencePackage(input);
  }

  async getEvidencePackage(input: Parameters<PackageRepository['getEvidencePackage']>[0]): Promise<Awaited<ReturnType<PackageRepository['getEvidencePackage']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEvidencePackage(input);
  }
}
