/**
 * PublicationHoldRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PublicationHoldRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PublicationHoldRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PublicationHoldRepository,
} from "@cutpoint/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PublicationHoldRepositoryDdb } from "./publication-hold-repository.ddb.js";

/**
 * PublicationHoldRepositoryAdapter
 *
 * Implements PublicationHoldRepository port for infrastructure layer.
 */
export class PublicationHoldRepositoryAdapter implements PublicationHoldRepository {
  private readonly ddb: PublicationHoldRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PublicationHoldRepositoryDdb(this.dynamoClient);
  }

  async listPublicationHolds(input: Parameters<PublicationHoldRepository['listPublicationHolds']>[0]): Promise<Awaited<ReturnType<PublicationHoldRepository['listPublicationHolds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPublicationHolds(input);
  }
}
