/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Markets Domain Use Cases
 * 
 * List of all use case names for the markets domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const MARKETS_USE_CASES = [
  "executeGetMarket",
  "executeIngestCorpus",
  "executeListCorpora",
  "executeListMarkets",
  "executeRegisterMarket"
] as const;
