/**
 * Corpora DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Corpora DTOs
 *
 * DDD: Application DTOs for Corpora use cases.
 */

import type { IngestCorpusParams, IngestCorpusRequestInput, ListCorporaParams } from "@cutpoint/core/markets/types";

export type ListCorporaInput = ListCorporaParams;

export type IngestCorpusInput = IngestCorpusParams & IngestCorpusRequestInput;

export type ListCorporaOutput = {};

export type IngestCorpusOutput = {};
