/**
 * Market DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: markets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Market DTOs
 *
 * DDD: Application DTOs for Market use cases.
 */

import type { GetMarketParams, ListMarketsParams, RegisterMarketRequestInput } from "@cutpoint/core/markets/types";

export type ListMarketsInput = ListMarketsParams;

export type RegisterMarketInput = RegisterMarketRequestInput;

export type GetMarketInput = GetMarketParams;

export type ListMarketsOutput = {};

export type RegisterMarketOutput = {};

export type GetMarketOutput = {};
